export const mathematicsQuestions = [
  { category: "الرياضيات والمنطق", q: "ما هو ناتج مجموع زوايا المثلث الداخلية؟", a: "180 درجة", choices: ["90 درجة", "180 درجة", "360 درجة", "270 درجة"], difficulty: "super easy", points: 50, power: false },
  { category: "الرياضيات والمنطق", q: "ما هو الرقم الذي يمثل 'X' في المعادلة: 2x + 10 = 20؟", a: "5", choices: ["2", "5", "10", "8"], difficulty: "super easy", points: 50, power: false },
  { category: "الرياضيات والمنطق", q: "أي من الأعداد التالية يعتبر عدداً أولياً؟", a: "13", choices: ["9", "15", "13", "21"], difficulty: "easy", points: 100, power: false },
  { category: "الرياضيات والمنطق", q: "ما هو الجذر التربيعي للعدد 144؟", a: "12", choices: ["10", "14", "12", "16"], difficulty: "easy", points: 100, power: false },
  { category: "الرياضيات والمنطق", q: "كم دقيقة توجد في يوم ونصف؟", a: "2160 دقيقة", choices: ["1440 دقيقة", "2160 دقيقة", "1800 دقيقة", "2400 دقيقة"], difficulty: "medium", points: 150, power: false },
  { category: "الرياضيات والمنطق", q: "من هو العالم الملقب بـ 'أبو الجبر'؟", a: "الخوارزمي", choices: ["ابن سينا", "الخوارزمي", "فيثاغورس", "إقليدس"], difficulty: "easy", points: 100, power: false },
  { category: "الرياضيات والمنطق", q: "ما هو ناتج مضروب العدد 5 (5!)؟", a: "120", choices: ["100", "120", "60", "25"], difficulty: "medium", points: 150, power: false },
  { category: "الرياضيات والمنطق", q: "ما هي قيمة الثابت الرياضي 'pi' تقريباً لأول خانتين عشريتين؟", a: "3.14", choices: ["3.12", "3.16", "3.14", "3.18"], difficulty: "super easy", points: 50, power: false },
  { category: "الرياضيات والمنطق", q: "مكعب طول ضلعه 3 سم، ما هو حجمه؟", a: "27 سم³", choices: ["9 سم³", "18 سم³", "27 سم³", "81 سم³"], difficulty: "easy", points: 100, power: false },
  { category: "الرياضيات والمنطق", q: "لغز: أب عمره ثلاثة أضعاف عمر ابنه، وبعد 12 سنة سيصبح عمره ضعفي عمر ابنه. كم عمر الابن الآن؟", a: "12", choices: ["10", "12", "15", "18"], difficulty: "hard", points: 200, power: false },
  { category: "الرياضيات والمنطق", q: "ما هي النظرية التي تنص على أن مجموع مربعي ضلعي الزاوية القائمة يساوي مربع الوتر في المثلث القائم؟", a: "نظرية فيثاغورس", choices: ["نظرية تاليس", "نظرية فيثاغورس", "نظرية إقليدس", "نظرية باسكال"], difficulty: "easy", points: 100, power: false },
  { category: "الرياضيات والمنطق", q: "ما هو العدد الذي إذا ضربته في نفسه وأضفت إليه 5 كان الناتج 30؟", a: "5", choices: ["4", "5", "6", "7"], difficulty: "easy", points: 100, power: false },
  { category: "الرياضيات والمنطق", q: "من هو العالم العربي الذي يعتبر واضع أسس علم المثلثات الحديث؟", a: "البتاني", choices: ["الخوارزمي", "البتاني", "ابن الهيثم", "جابر بن حيان"], difficulty: "hard", points: 200, power: false },
  { category: "الرياضيات والمنطق", q: "ما هو الرقم التالي في المتسلسلة: 2، 6، 12، 20، 30...؟", a: "42", choices: ["35", "40", "42", "45"], difficulty: "medium", points: 150, power: false },
  { category: "الرياضيات والمنطق", q: "ما هو العدد 'الكامل' (الذي يساوي مجموع قواسمه باستثناء نفسه) الأصغر؟", a: "6", choices: ["1", "6", "28", "12"], difficulty: "hard", points: 200, power: false },
  { category: "الرياضيات والمنطق", q: "من هو الفيلسوف اليوناني الذي يعتبر مؤسس علم المنطق الصوري؟", a: "أرسطو", choices: ["أفلاطون", "سقراط", "أرسطو", "فيثاغورس"], difficulty: "medium", points: 150, power: false },
  { category: "الرياضيات والمنطق", q: "كم يساوي ناتج جمع الأعداد من 1 إلى 100؟", a: "5050", choices: ["5000", "5050", "5100", "4950"], difficulty: "hard", points: 200, power: false },
  { category: "الرياضيات والمنطق", q: "كم عدد أضلاع الشكل السداسي؟", a: "6", choices: ["5", "6", "7", "8"], difficulty: "super easy", points: 50, power: false }, // Proof: Basic geometry
  { category: "الرياضيات والمنطق", q: "كم عدد الأصفار في المليون؟", a: "6 أصفار", choices: ["5 أصفار", "6 أصفار", "7 أصفار", "9 أصفار"], difficulty: "super easy", points: 50, power: false }, // Proof: 1,000,000 has 6 zeros
  { category: "الرياضيات والمنطق", q: "ما هو ناتج ضرب 7 × 8؟", a: "56", choices: ["48", "54", "56", "64"], difficulty: "super easy", points: 50, power: false }, // Proof: 7*8=56
  { category: "الرياضيات والمنطق", q: "ما هو الشكل الهندسي الذي ليس له زوايا أو أضلاع؟", a: "الدائرة", choices: ["المربع", "الدائرة", "المثلث", "المعين"], difficulty: "super easy", points: 50, power: false }, // Proof: Circle properties
  { category: "الرياضيات والمنطق", q: "ما هو الكسر الذي يمثل نصف الربع؟", a: "1/8 (ثمن)", choices: ["1/2 (نصف)", "1/3 (ثلث)", "1/6 (سدس)", "1/8 (ثمن)"], difficulty: "medium", points: 150, power: false }, // Proof: 1/2 * 1/4 = 1/8
  { category: "الرياضيات والمنطق", q: "ما هو ناتج قسمة أي عدد (غير الصفر) على نفسه؟", a: "1", choices: ["0", "1", "العدد نفسه", "عشرة"], difficulty: "super easy", points: 50, power: false }, // Proof: x/x = 1
  { category: "الرياضيات والمنطق", q: "كم عدد زوايا المربع؟", a: "4", choices: ["3", "4", "5", "6"], difficulty: "super easy", points: 50, power: false }, // Proof: Basic geometry
  { category: "الرياضيات والمنطق", q: "ما هو العدد الأولي الزوجي الوحيد؟", a: "2", choices: ["0", "2", "4", "6"], difficulty: "easy", points: 100, power: false }, // Proof: 2 is the only even prime
  { category: "الرياضيات والمنطق", q: "كم يبلغ مجموع زوايا المربع الداخلية؟", a: "360 درجة", choices: ["180 درجة", "270 درجة", "360 درجة", "400 درجة"], difficulty: "easy", points: 100, power: false }, // Proof: 4*90=360
  { category: "الرياضيات والمنطق", q: "ما هي وحدة قياس الزوايا الشائعة؟", a: "الدرجة", choices: ["السنتيمتر", "الدرجة", "اللتر", "الجرام"], difficulty: "easy", points: 100, power: false }, // Proof: Degrees measure angles
  { category: "الرياضيات والمنطق", q: "ما هو ناتج 9 × 9؟", a: "81", choices: ["72", "81", "90", "99"], difficulty: "super easy", points: 50, power: false }, // Proof: 9*9=81
  { category: "الرياضيات والمنطق", q: "إذا كان سعر القلم 5 ريالات واشتريت 4 أقلام، كم تدفع الإجمالي؟", a: "20 ريالاً", choices: ["15 ريالاً", "20 ريالاً", "25 ريالاً", "30 ريالاً"], difficulty: "super easy", points: 50, power: false }, // Proof: 5*4=20
  { category: "الرياضيات والمنطق", q: "كم سنتيمتراً يوجد في المتر الواحد؟", a: "100 سنتيمتر", choices: ["10 سنتيمترات", "50 سنتيمتراً", "100 سنتيمتر", "1000 سنتيمتر"], difficulty: "super easy", points: 50, power: false }, // Proof: 1m = 100cm
  { category: "الرياضيات والمنطق", q: "ما هو العدد الذي يسبق المليار مباشرة؟", a: "999,999,999", choices: ["99,999,999", "999,999,999", "1,000,000,001", "9,999,999"], difficulty: "easy", points: 100, power: false }, // Proof: 1,000,000,000 - 1
  { category: "الرياضيات والمنطق", q: "ماذا يسمى الخط المستقيم الذي يصل بين نقطتين على الدائرة ويمر بمركزها؟", a: "القطر", choices: ["الوتر", "القطر", "نصف القطر", "المماس"], difficulty: "easy", points: 100, power: false }, // Proof: Definition of diameter
  { category: "الرياضيات والمنطق", q: "كم جراماً يوجد في الكيلوجرام الواحد؟", a: "1000 جرام", choices: ["100 جرام", "500 جرام", "1000 جرام", "10000 جرام"], difficulty: "super easy", points: 50, power: false }, // Proof: 1kg = 1000g
  { category: "الرياضيات والمنطق", q: "ما هو الكسر الذي يمثل النصف؟", a: "1/2", choices: ["1/3", "1/4", "1/2", "3/4"], difficulty: "super easy", points: 50, power: false }, // Proof: 1/2 is half
  { category: "الرياضيات والمنطق", q: "في المثلث متساوي الأضلاع، كم يبلغ قياس كل زاوية داخلية؟", a: "60 درجة", choices: ["45 درجة", "60 درجة", "90 درجة", "180 درجة"], difficulty: "easy", points: 100, power: false }, // Proof: 180/3 = 60
  { category: "الرياضيات والمنطق", q: "ما هو العدد الوحيد الذي لا يعتبر موجباً ولا سالباً؟", a: "الصفر", choices: ["1", "-1", "الصفر", "10"], difficulty: "super easy", points: 50, power: false }, // Proof: 0 is neutral
  { category: "الرياضيات والمنطق", q: "إذا كانت الساعة تماماً 3:00، ما هي الزاوية الصغرى بين عقرب الساعات وعقرب الدقائق؟", a: "90 درجة", choices: ["45 درجة", "60 درجة", "90 درجة", "180 درجة"], difficulty: "medium", points: 150, power: false }, // Proof: 3 hours * 30 degrees = 90
  { category: "الرياضيات والمنطق", q: "كم عدد الدقائق في ساعتين؟", a: "120 دقيقة", choices: ["60 دقيقة", "90 دقيقة", "120 دقيقة", "150 دقيقة"], difficulty: "super easy", points: 50, power: false }, // Proof: 2 * 60 = 120
  { category: "الرياضيات والمنطق", q: "ما هو ناتج قسمة 15 على 3؟", a: "5", choices: ["3", "4", "5", "6"], difficulty: "super easy", points: 50, power: false }, // Proof: 15 / 3 = 5
  { category: "الرياضيات والمنطق", q: "ما هو أصغر عدد صحيح موجب مكون من 3 منازل (خانات)؟", a: "100", choices: ["001", "100", "111", "999"], difficulty: "easy", points: 100, power: false }, // Proof: 100 is the smallest 3-digit positive int
  { category: "الرياضيات والمنطق", q: "كم شهراً يوجد في 3 سنوات؟", a: "36 شهراً", choices: ["24 شهراً", "30 شهراً", "36 شهراً", "48 شهراً"], difficulty: "super easy", points: 50, power: false }, // Proof: 3 * 12 = 36
  { category: "الرياضيات والمنطق", q: "ما هو العنصر المحايد في عملية الضرب؟", a: "1", choices: ["0", "1", "2", "-1"], difficulty: "easy", points: 100, power: false }, // Proof: x * 1 = x
  { category: "الرياضيات والمنطق", q: "ما هو العنصر المحايد في عملية الجمع؟", a: "الصفر", choices: ["1", "-1", "الصفر", "10"], difficulty: "easy", points: 100, power: false }, // Proof: x + 0 = x
  { category: "الرياضيات والمنطق", q: "ما هي النسبة المئوية التي تعادل الكسر 1/4؟", a: "25%", choices: ["20%", "25%", "50%", "75%"], difficulty: "easy", points: 100, power: false }, // Proof: 1/4 = 0.25 = 25%
  { category: "الرياضيات والمنطق", q: "أي من الأشكال الهندسية التالية يتكون من 5 أضلاع؟", a: "الخماسي", choices: ["الرباعي", "الخماسي", "السداسي", "المثمن"], difficulty: "super easy", points: 50, power: false }, // Proof: Pentagon has 5 sides
  { category: "الرياضيات والمنطق", q: "إذا كان محيط مربع يساوي 20 سم، فكم يبلغ طول ضلعه؟", a: "5 سم", choices: ["4 سم", "5 سم", "10 سم", "16 سم"], difficulty: "easy", points: 100, power: false }, // Proof: 20 / 4 = 5
  { category: "الرياضيات والمنطق", q: "كم ميليمتراً يوجد في السنتيمتر الواحد؟", a: "10", choices: ["5", "10", "100", "1000"], difficulty: "easy", points: 100, power: false }, // Proof: 1cm = 10mm
  { category: "الرياضيات والمنطق", q: "ما هو ناتج 10 أس 3 (10³)؟", a: "1000", choices: ["30", "100", "1000", "10000"], difficulty: "easy", points: 100, power: false }, // Proof: 10*10*10 = 1000
  { category: "الرياضيات والمنطق", q: "ما هو الرقم الذي يكمل هذه المتتالية: 1، 3، 5، 7، ...؟", a: "9", choices: ["8", "9", "10", "11"], difficulty: "super easy", points: 50, power: false }, // Proof: Odd numbers sequence
  { category: "الرياضيات والمنطق", q: "كم يوماً في السنة الكبيسة؟", a: "366 يوماً", choices: ["364 يوماً", "365 يوماً", "366 يوماً", "360 يوماً"], difficulty: "easy", points: 100, power: false } // Proof: Leap year has 366 days
];