export const mythsAndLegendsQuestions = [
  { category: "أساطير وخرافات", q: "ما هو الكائن الأسطوري السحري الذي يخرج من المصباح في حكايات 'علاء الدين'؟", a: "الجني", choices: ["الغول", "العنقاء", "الجني", "النسناس"], difficulty: "super easy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/علاء_الدين
  { category: "أساطير وخرافات", q: "في حكايات 'ألف ليلة وليلة'، من هي البطلة الذكية التي تروي القصص للملك شهريار لتنجو بحياتها؟", a: "شهرزاد", choices: ["دنيازاد", "شهرزاد", "مرجانة", "بدر البدور"], difficulty: "super easy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/ألف_ليلة_وليلة
  { category: "أساطير وخرافات", q: "من هو البطل الشعبي الذي واجه عصابة 'الأربعين حرامي' بكلمة السر 'افتح يا سمسم'؟", a: "علي بابا", choices: ["علاء الدين", "السندباد", "علي بابا", "أبو زيد الهلالي"], difficulty: "super easy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/علي_بابا_والأربعون_لصا
  { category: "أساطير وخرافات", q: "كائن خرافي شهير يعيش في قصور ترانسيلفانيا ويشرب الدماء ولا يظهر في المرايا؟", a: "مصاص الدماء (دراكولا)", choices: ["المستذئب", "مصاص الدماء (دراكولا)", "الزومبي", "الفرانكنشتاين"], difficulty: "super easy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/دراكولا
  { category: "أساطير وخرافات", q: "كائن أسطوري ضخم يشبه الزواحف، يطير في السماء وينفث النار من فمه؟", a: "التنين", choices: ["الغول", "الكراكن", "العنقاء", "التنين"], difficulty: "super easy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/تنين
  { category: "أساطير وخرافات", q: "ما هو الكائن الخرافي الذي يمتلك نصفه العلوي شكل امرأة ونصفه السفلي ذيل سمكة؟", a: "حورية البحر", choices: ["السايرن", "حورية البحر", "الجنية", "العنقاء"], difficulty: "super easy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/حورية_البحر
  { category: "أساطير وخرافات", q: "في الخرافات الشعبية، ماذا تركب الساحرة الشريرة لتطير في الهواء؟", a: "مكنسة سحرية", choices: ["سجادة طائرة", "مكنسة سحرية", "حصان مجنح", "تنين"], difficulty: "super easy", points: 50, power: false }, // Source: Cultural folklore regarding witches
  { category: "أساطير وخرافات", q: "في الأساطير، إلى ماذا يتحول الإنسان المصاب بلعنة عندما يكتمل القمر ليصبح بدراً؟", a: "مستذئب", choices: ["مصاص دماء", "مستذئب", "شبح", "خفاش"], difficulty: "super easy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/مستذئب
  { category: "أساطير وخرافات", q: "من هو إله الصواعق وملك الآلهة في الأساطير الإغريقية؟", a: "زيوس", choices: ["زيوس", "أبولو", "هاديس", "بوسيدون"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/زيوس
  { category: "أساطير وخرافات", q: "في الأساطير الإسكندنافية، من هو إله الرعد الذي يحمل مطرقة سحرية شهيرة؟", a: "ثور", choices: ["أودين", "ثور", "لوكي", "بالدر"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/ثور_(ميثولوجيا)
  { category: "أساطير وخرافات", q: "ما هو الطائر الأسطوري الذي يشتعل بالنار ويولد من رماده مجدداً؟", a: "العنقاء", choices: ["الرخ", "الغراب", "العنقاء", "الهدهد"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/عنقاء
  { category: "أساطير وخرافات", q: "ما اسم الغول المخيف في التراث الشعبي المصري والخليجي الذي يُخوّف به الأطفال المشاغبون؟", a: "البعبع", choices: ["أبو رجل مسلوخة", "حمارة القايلة", "البعبع", "الطنطل"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/بعبع
  { category: "أساطير وخرافات", q: "في الأساطير العربية القديمة، ما هو الكائن الذي يمثل ذروة القبح والوحشية ويأكل البشر؟", a: "الغول", choices: ["الجن", "الغول", "النسناس", "العفريت"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/غول
  { category: "أساطير وخرافات", q: "ما اسم الوحش الإغريقي الذي يمتلك شعراً من الأفاعي الحية ويحول الناظر إليه إلى حجر؟", a: "ميدوسا", choices: ["سيرين", "ميدوسا", "هيدرا", "شيميرا"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/ميدوسا
  { category: "أساطير وخرافات", q: "من هو إله الشمس وأهم الآلهة في مصر القديمة والذي يُمثل بقرص الشمس؟", a: "رع", choices: ["آمون", "رع", "ست", "تحوت"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/رع
  { category: "أساطير وخرافات", q: "ما هو الكائن الأسطوري الذي يمتلك جسد حصان أبيض وجناحي نسر عملاقين؟", a: "بيغاسوس", choices: ["القنطور", "بيغاسوس", "الغريفين", "العنقاء"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/بيغاسوس
  { category: "أساطير وخرافات", q: "من هو بطل الروايات والرحلات البحرية السبع الأسطورية في كتاب 'ألف ليلة وليلة'؟", a: "السندباد", choices: ["علاء الدين", "علي بابا", "شهريار", "السندباد"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/السندباد_البحري
  { category: "أساطير وخرافات", q: "ما اسم الأسطورة الإنجليزية للرامي الماهر الذي يسرق من الأغنياء ليعطي الفقراء؟", a: "روبن هود", choices: ["الملك آرثر", "روبن هود", "ويليام والاس", "بيتر بان"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/روبن_هود
  { category: "أساطير وخرافات", q: "من هو الملك البريطاني الأسطوري الذي سحب السيف السحري من الصخرة؟", a: "الملك آرثر", choices: ["الملك ريتشارد", "الملك آرثر", "لانسلوت", "ميرلين"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/الملك_آرثر
  { category: "أساطير وخرافات", q: "ما اسم الوحش المائي الأسطوري الذي يُشاع أنه يعيش في بحيرة اسكتلندية عميقة؟", a: "وحش لوخ نيس", choices: ["الكراكن", "وحش لوخ نيس", "الميغالودون", "الليفاياثان"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/وحش_لوخ_نيس
  { category: "أساطير وخرافات", q: "من هو البطل الإغريقي نصف الإله، ابن زيوس، المشهور بقوته الجبارة وإنجازاته الاثني عشر؟", a: "هرقل", choices: ["أخيل", "ثيسيوس", "بيرسيوس", "هرقل"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/هرقل
  { category: "أساطير وخرافات", q: "من هو إله الحب عند الرومان الذي يُصور كطفل مجنح يحمل قوساً وسهاماً؟", a: "كيوبيد", choices: ["أبولو", "آريس", "كيوبيد", "هيرميس"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/كيوبيد
  { category: "أساطير وخرافات", q: "ما هو التمثال المصري الأسطوري الذي يمتلك جسد أسد رابض ورأس إنسان؟", a: "أبو الهول", choices: ["أنوبيس", "أبو الهول", "حورس", "الباستيت"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/أبو_الهول
  { category: "أساطير وخرافات", q: "ما هي الأسطورة المصرية المرعبة لامرأة جميلة تنادي الأشخاص بأسمائهم ليلاً في الحقول لتغرقهم؟", a: "النداهة", choices: ["أمنا الغولة", "النداهة", "السعلوة", "الجنية"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/النداهة
  { category: "أساطير وخرافات", q: "ما اسم الجنية أو المرأة الجميلة في الأساطير الخليجية التي تخفي أرجل حمار تحت ثيابها وتجذب الرجال لقتلهم؟", a: "أم الدويس", choices: ["حمارة القايلة", "السعلوة", "أم الدويس", "الطنطل"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/أم_الدويس
  { category: "أساطير وخرافات", q: "ما اسم إله البحر والزلازل في الأساطير الإغريقية الذي يحمل رمحاً ثلاثي الشعب؟", a: "بوسيدون", choices: ["زيوس", "هاديس", "أبولو", "بوسيدون"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/بوسيدون
  { category: "أساطير وخرافات", q: "من هو إله العالم السفلي والموتى في الميثولوجيا الإغريقية؟", a: "هاديس", choices: ["أوزوريس", "هاديس", "أنوبيس", "ست"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/هاديس
  { category: "أساطير وخرافات", q: "ما هي الحيلة الأسطورية الخشبية العملاقة التي استخدمها الإغريق لاقتحام مدينة محصنة؟", a: "حصان طروادة", choices: ["منجنيق إسبارطة", "حصان طروادة", "كبش الفداء", "فيل هانيبال"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/حصان_طروادة
  { category: "أساطير وخرافات", q: "أي طائر يرتبط ارتباطاً وثيقاً بالتشاؤم ونذير الموت في الخرافات العربية القديمة؟", a: "الغراب", choices: ["البومة", "النسر", "الغراب", "الخفاش"], difficulty: "easy", points: 100, power: false }, // Source: Cultural folklore regarding ravens/crows
  { category: "أساطير وخرافات", q: "من هو البطل الإغريقي الذي لا يُقهر إلا في نقطة واحدة بجسده (كعبه)؟", a: "أخيل", choices: ["هيكتور", "باريس", "هرقل", "أخيل"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/أخيل
  { category: "أساطير وخرافات", q: "ما اسم كبير الآلهة في الأساطير الإسكندنافية الذي يمتلك عيناً واحدة وغرابين على كتفيه؟", a: "أودين", choices: ["ثور", "لوكي", "أودين", "تير"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/أودين
  { category: "أساطير وخرافات", q: "ما هو المخلوق الأسطوري الصغير الذي يشتهر في الأساطير الأيرلندية بتخزين الذهب عند نهاية قوس قزح؟", a: "ليبريكون", choices: ["الجني", "القزم", "ليبريكون", "الغول"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/ليبريكون
  { category: "أساطير وخرافات", q: "ما هي الوسيلة السحرية التي يتنقل بها 'علاء الدين' في الهواء؟", a: "بساط الريح", choices: ["المكنسة الطائرة", "الحصان المجنح", "بساط الريح", "النسر العملاق"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/بساط_الريح
  { category: "أساطير وخرافات", q: "في التراث الشعبي الشامي والمصري، ما هي قصة الشاب الذي تربى في الغابة وأصبح 'ملك الغابة'؟", a: "طرزان", choices: ["ماوكلي", "طرزان", "روبن هود", "بيتر بان"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/طرزان
  { category: "أساطير وخرافات", q: "ما هو الكائن الطائر الضخم جداً في الخرافات العربية الذي يستطيع حمل فيل كامل؟", a: "طائر الرخ", choices: ["العنقاء", "طائر الرخ", "البيغاسوس", "التنين"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/رخ_(طائر_أسطوري)
  { category: "أساطير وخرافات", q: "ما اسم الوحش ذي العين الواحدة العملاقة في الأساطير اليونانية؟", a: "السيكلوب", choices: ["المينوتور", "القنطور", "السيكلوب", "الغول"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/سايكلوب
  { category: "أساطير وخرافات", q: "ما اسم البطل الإغريقي الذي دخل المتاهة المظلمة وهزم وحش 'المينوتور'؟", a: "ثيسيوس", choices: ["هرقل", "أخيل", "ثيسيوس", "بيرسيوس"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/ثيسيوس
  { category: "أساطير وخرافات", q: "من هو إله التحنيط وحارس الموتى ذو رأس ابن آوى في الأساطير المصرية؟", a: "أنوبيس", choices: ["رع", "حورس", "أنوبيس", "أوزوريس"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/أنوبيس
  { category: "أساطير وخرافات", q: "ما اسم الكائن البحري العملاق ذي اللوامس المتعددة الذي يغرق السفن في أساطير الشمال؟", a: "الكراكن", choices: ["لوياثان", "الكراكن", "السايرن", "التنين"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/كراكن
  { category: "أساطير وخرافات", q: "ما اسم الكائن الأسطوري المرعب في التراث الكويتي والخليجي الذي يظهر في وقت الظهيرة الحارقة؟", a: "حمارة القايلة", choices: ["السعلوة", "حمارة القايلة", "الطنطل", "بودرياه"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/حمارة_القايلة
  { category: "أساطير وخرافات", q: "ماذا يسمى المخلوق أو العفريت الذي يسكن أعماق البحر ويخطف أو يغرق البحارة في التراث الخليجي؟", a: "بودرياه (بابا درياه)", choices: ["بودرياه (بابا درياه)", "الدجال", "خطاف الرفاي", "أم الدويس"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/بابا_درياه
  { category: "أساطير وخرافات", q: "من هو الفارس والبطل الشعبي العربي صاحب السيرة العظيمة التي تحكي 'تغريبة بني هلال'؟", a: "أبو زيد الهلالي", choices: ["الظاهر بيبرس", "عنترة بن شداد", "أبو زيد الهلالي", "سيف بن ذي يزن"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/أبو_زيد_الهلالي
  { category: "أساطير وخرافات", q: "ما اسم الكائن الأسطوري الإغريقي الذي يمتلك نصفه الأعلى جسد إنسان ونصفه الأسفل حصان؟", a: "القنطور", choices: ["ساتير", "المينوتور", "القنطور", "بيغاسوس"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/قنطور
  { category: "أساطير وخرافات", q: "ما اسم السيف الأسطوري الذي سحبه الملك آرثر والذي يمنح حامله قوة لا تقهر؟", a: "إكسكاليبر", choices: ["إكسكاليبر", "جرام", "مورغلاي", "دورانْدال"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/إكسكاليبر
  { category: "أساطير وخرافات", q: "حسب الأسطورة الإغريقية، ما هو الشيء الذي فُتح وأخرج جميع الشرور والأمراض إلى العالم؟", a: "صندوق باندورا", choices: ["كأس هيرا", "صندوق باندورا", "بوابة هاديس", "تفاحة إيريس"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/صندوق_باندورا
  { category: "أساطير وخرافات", q: "من هي إلهة السحر والأمومة والشفاء في الأساطير المصرية القديمة، وزوجة أوزوريس؟", a: "إيزيس", choices: ["حتحور", "نفتيس", "إيزيس", "سخمت"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/إيزيس
  { category: "أساطير وخرافات", q: "من هو الإله المصري القديم الذي يُصور برأس صقر ويعتبر إله السماء والانتقام؟", a: "حورس", choices: ["رع", "أنوبيس", "ست", "حورس"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/حورس
  { category: "أساطير وخرافات", q: "من هو الإله المصري الذي قُتل وقُطع على يد أخيه 'ست' ثم أصبح حاكم العالم السفلي؟", a: "أوزوريس", choices: ["حورس", "أنوبيس", "أوزوريس", "بتاح"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/أوزوريس
  { category: "أساطير وخرافات", q: "ما هو الكائن الأسطوري الذي يمتلك جسد أسد، ورأس وجناحي نسر عملاق ويعتبر حارساً للكنوز؟", a: "الغريفين (الفَتْخَاء)", choices: ["البيغاسوس", "المانتيكور", "الكيميرا", "الغريفين (الفَتْخَاء)"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/غريفين
  { category: "أساطير وخرافات", q: "من هو الشخصية الأسطورية الإغريقية الذي عوقب بدحرجة صخرة عملاقة إلى قمة جبل لتعود وتسقط للأبد؟", a: "سيزيف", choices: ["أطلس", "بروميثيوس", "سيزيف", "تانتالوس"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/سيزيف
  { category: "أساطير وخرافات", q: "ما هي الشخصية الخرافية المرعبة في التراث العربي (وخاصة العراقي والشامي) التي تشبه الغول ولكنها أنثى شديدة الدهاء؟", a: "السعلوة", choices: ["النداهة", "أم الدويس", "الطنطل", "السعلوة"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/سعلوة
  { category: "أساطير وخرافات", q: "ما اسم الكلب المتوحش ذي الرؤوس الثلاثة الذي يحرس بوابات العالم السفلي في الأساطير اليونانية؟", a: "سيربيروس", choices: ["أورثوس", "شيميرا", "سيربيروس", "هاوند"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/سيربيروس
  { category: "أساطير وخرافات", q: "من هو إله الخداع والمكر والتحول في الأساطير الإسكندنافية (النوردية)؟", a: "لوكي", choices: ["أودين", "ثور", "بالدر", "لوكي"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/لوكي
  { category: "أساطير وخرافات", q: "ما هو اسم القاعة العظيمة في الأساطير الإسكندنافية التي يذهب إليها المحاربون الشجعان بعد موتهم في المعركة؟", a: "فالهالا", choices: ["أسغارد", "مدغارد", "هيلهيم", "فالهالا"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/فالهالا
  { category: "أساطير وخرافات", q: "من هو البطل العربي والفارس الشاعر الذي نسجت حول قوته وبطولاته ملاحم شعبية طويلة ليفوز بابنة عمه عبلة؟", a: "عنترة بن شداد", choices: ["الزير سالم", "عنترة بن شداد", "سيف بن ذي يزن", "أبو زيد الهلالي"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/عنترة_بن_شداد
  { category: "أساطير وخرافات", q: "في الأساطير اليونانية، من هو التيتان الذي سرق النار من الآلهة وأعطاها للبشر فعوقب بربطه في صخرة؟", a: "بروميثيوس", choices: ["أطلس", "كرونوس", "بروميثيوس", "سيزيف"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/بروميثيوس
  { category: "أساطير وخرافات", q: "ما هي الأسطورة العربية التي تتحدث عن ملك حكم الجن والشياطين وامتلك بساطاً ينقله حيث يشاء بخاتم سحري؟", a: "خاتم سليمان", choices: ["مصباح علاء الدين", "عصا موسى", "خاتم سليمان", "كنز قارون"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/خاتم_سليمان
  { category: "أساطير وخرافات", q: "ما اسم الملحمة البابلية الأقدم في التاريخ التي تروي قصة ملك يبحث عن عشبة الخلود بعد موت صديقه إنكيدو؟", a: "ملحمة جلجامش", choices: ["ملحمة الإلياذة", "ملحمة جلجامش", "ملحمة الأوديسة", "الإنيادة"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/ملحمة_جلجامش
  { category: "أساطير وخرافات", q: "ما هو اسم وحش البحر العظيم والأفعى الملتوية المذكورة في الأساطير الدينية القديمة (العهد القديم)؟", a: "لوياثان", choices: ["كراكن", "بيهيموث", "لوياثان", "ميدغارد"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/لوياثان
  { category: "أساطير وخرافات", q: "في الميثولوجيا الإسكندنافية، ما اسم 'شجرة الحياة' الكونية الرمادية العملاقة التي تربط العوالم التسعة؟", a: "يغدراسيل", choices: ["فالهالا", "يغدراسيل", "بيفروست", "راجناروك"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/يغدراسيل
  { category: "أساطير وخرافات", q: "ما اسم الإله الرئيسي في حضارة الأزتيك والمكسيك القديمة، والذي يُصوّر على هيئة 'ثعبان مغطى بالريش'؟", a: "كيتزالكواتل", choices: ["كوكولكان", "هويتزيلوبوتشتلي", "كيتزالكواتل", "تلالوك"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/كويتزالكواتل
  { category: "أساطير وخرافات", q: "ما هو المصطلح في الأساطير النوردية (الإسكندنافية) الذي يعني المعركة النهائية ونهاية العالم وموت الآلهة الكبرى؟", a: "راجناروك", choices: ["أرمجدون", "راجناروك", "فيمبولفينتر", "أسغارد"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/راجناروك
  { category: "أساطير وخرافات", q: "في أساطير الهنود الحمر (أمريكا الشمالية)، ما هو الروح الشريرة أو الوحش المرتبط بالشتاء والمجاعة وأكل لحوم البشر؟", a: "وينديجو", choices: ["ساسكواتش", "وينديجو", "ثندربيرد", "شيبشيفتر"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/وينديجو
  { category: "أساطير وخرافات", q: "ما هو الكائن الزاحف الأسطوري الذي يُلقب بـ 'ملك الأفاعي' والذي يمكن أن يقتل ضحيته بنظرة واحدة فقط؟", a: "الباسيليسك", choices: ["الهيدرا", "الكوكاتريس", "الباسيليسك", "تيفون"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/باسيليسك
  { category: "أساطير وخرافات", q: "ما هو الوحش الإغريقي الذي يتنفس النار، ويتكون جسده من أجزاء ثلاثة حيوانات (أسد، ماعز، وأفعى كذيل)؟", a: "الكيميرا (الخيمر)", choices: ["الهيدرا", "السيربيروس", "المانتيكور", "الكيميرا (الخيمر)"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/خيمر
  { category: "أساطير وخرافات", q: "في الفولكلور اليهودي، ما هو المخلوق المصنوع من الطين أو الوحل الذي يتم إحياؤه باستخدام تعويذات سحرية لحماية الناس؟", a: "الغوليم", choices: ["الجن", "الغوليم", "الديوك", "الشيطان"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/غولم
  { category: "أساطير وخرافات", q: "في الفولكلور الياباني، ما هو شيطان الماء الذي يشبه السلحفاة ويمتلك تجويفاً ممتلئاً بالماء فوق رأسه يستمد منه طاقته؟", a: "كابا", choices: ["تنجو", "يوراي", "أوني", "كابا"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/كابا_(فولكلور)
  { category: "أساطير وخرافات", q: "من هو القبطان الأسطوري الذي يحكم أعماق البحار، ويُقال إن أرواح البحارة الغرقى تُحفظ في 'خزانته' المظلمة؟", a: "ديفي جونز", choices: ["بلاك بيرد", "ديفي جونز", "كابتن كيد", "الكراكن"], difficulty: "hard", points: 200, power: false } // Source: https://ar.wikipedia.org/wiki/ديفي_جونز
];