export const physicsQuestions = [
  { category: "الفيزياء", q: "ما هي القوة الخفية التي تسقط الأشياء وتثبتنا على الأرض؟", a: "الجاذبية", choices: ["المغناطيسية", "الاحتكاك", "الجاذبية", "الطرد المركزي"], difficulty: "supereasy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/جاذبية
  { category: "الفيزياء", q: "ما هي درجة الحرارة المئوية التي يغلي عندها الماء النقي؟", a: "100 درجة مئوية", choices: ["50 درجة مئوية", "100 درجة مئوية", "150 درجة مئوية", "200 درجة مئوية"], difficulty: "supereasy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/نقطة_الغليان
  { category: "الفيزياء", q: "ما هي درجة الحرارة المئوية التي يتجمد عندها الماء النقي؟", a: "صفر مئوية", choices: ["صفر مئوية", "10 تحت الصفر", "5 مئوية", "20 تحت الصفر"], difficulty: "supereasy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/نقطة_الانصهار
  { category: "الفيزياء", q: "ما هو المعدن الأكثر شهرة الذي ينجذب بقوة للمغناطيس؟", a: "الحديد", choices: ["النحاس", "الألمنيوم", "الذهب", "الحديد"], difficulty: "supereasy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/مغناطيسية_حديدية
  { category: "الفيزياء", q: "عند حدوث البرق والرعد معاً، أيهما نلاحظه أولاً؟", a: "البرق (الضوء أسرع)", choices: ["الرعد (الصوت أسرع)", "البرق (الضوء أسرع)", "نلاحظهما في نفس اللحظة", "يعتمد على قوة العاصفة"], difficulty: "supereasy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/برق
  { category: "الفيزياء", q: "ماذا يحدث للثلج عندما يكتسب طاقة حرارية؟", a: "ينصهر (يذوب)", choices: ["يتجمد", "ينصهر (يذوب)", "يتكثف", "يتبلور"], difficulty: "supereasy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/انصهار
  { category: "الفيزياء", q: "ماذا يسمى القوس الملون الذي يظهر في السماء بعد هطول المطر وشروق الشمس؟", a: "قوس قزح", choices: ["هالة الشمس", "قوس قزح", "الشفق القطبي", "السراب"], difficulty: "supereasy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/قوس_قزح
  { category: "الفيزياء", q: "ما هو المصدر الأساسي والرئيسي للطاقة والحرارة على كوكب الأرض؟", a: "الشمس", choices: ["الرياح", "البراكين", "الشمس", "لب الأرض"], difficulty: "supereasy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/طاقة_شمسية
  { category: "الفيزياء", q: "الأجسام التي تطفو فوق سطح الماء، تكون كثافتها مقارنة بالماء...؟", a: "أقل من الماء", choices: ["أكبر من الماء", "مساوية للماء", "أقل من الماء", "لا علاقة للكثافة"], difficulty: "supereasy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/طفو
  { category: "الفيزياء", q: "ماذا تسمى المواد التي تسمح للكهرباء بالمرور عبرها بسهولة (مثل النحاس)؟", a: "مواد موصلة", choices: ["مواد عازلة", "مواد موصلة", "مواد مشعة", "مواد مغناطيسية"], difficulty: "supereasy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/موصل_كهربائي
  { category: "الفيزياء", q: "ما هي الوحدة الأساسية المستخدمة لقياس القوة في الفيزياء؟", a: "النيوتن", choices: ["الجول", "الواط", "النيوتن", "الأمبير"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/نيوتن_(وحدة)
  { category: "الفيزياء", q: "ما هو الجهاز الكلاسيكي المستخدم لقياس درجة حرارة الجسم أو الجو؟", a: "الترمومتر", choices: ["البارومتر", "الترمومتر", "الأميتر", "الفولتميتر"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/مقياس_حرارة
  { category: "الفيزياء", q: "أي من هذه المواد تعتبر عازلة للتيار الكهربائي؟", a: "المطاط", choices: ["الحديد", "النحاس", "المطاط", "الفضة"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/عازل_كهربائي
  { category: "الفيزياء", q: "ماذا تسمى العملية التي يتحول فيها الماء من الحالة السائلة إلى الغازية؟", a: "التبخر", choices: ["التكثف", "الانصهار", "التبخر", "التجمد"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/تبخر
  { category: "الفيزياء", q: "ما هو اللون الذي يمتص أكبر قدر من حرارة الشمس؟", a: "الأسود", choices: ["الأبيض", "الأصفر", "الأسود", "الأحمر"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/جسم_أسود
  { category: "الفيزياء", q: "أي قطبين مغناطيسيين يتنافران ويبتعدان عن بعضهما؟", a: "المتشابهان (شمالي مع شمالي)", choices: ["المختلفان (شمالي مع جنوبي)", "المتشابهان (شمالي مع شمالي)", "جميع الأقطاب تتنافر", "المغناطيس لا يتنافر أبداً"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/مغناطيس
  { category: "الفيزياء", q: "ماذا يسمى الارتداد الفجائي للضوء عندما يصطدم بمرآة أو سطح مصقول؟", a: "الانعكاس", choices: ["الانكسار", "الحيود", "الانعكاس", "التشتت"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/انعكاس_(فيزياء)
  { category: "الفيزياء", q: "هل يمكن للصوت أن ينتقل في الفراغ الخارجي (في الفضاء)؟", a: "لا، يحتاج لوسط مادي", choices: ["نعم، وبسرعة أكبر", "لا، يحتاج لوسط مادي", "نعم، ولكن ببطء شديد", "ينتقل فقط إذا كان عالياً"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/صوت
  { category: "الفيزياء", q: "ماذا يسمى الجسم الشفاف الذي يحلل الضوء الأبيض إلى ألوان الطيف السبعة؟", a: "المنشور الزجاجي", choices: ["العدسة المحدبة", "المرآة المقعرة", "المنشور الزجاجي", "التلسكوب"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/موشور_(بصريات)
  { category: "الفيزياء", q: "ما هي الوحدة التي نقيس بها فرق الجهد الكهربائي؟", a: "الفولت", choices: ["الأمبير", "الفولت", "الأوم", "الواط"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/فولت
  { category: "الفيزياء", q: "ما هي الطاقة التي يمتلكها الجسم بسبب حركته وسرعته؟", a: "طاقة حركية", choices: ["طاقة وضع", "طاقة حركية", "طاقة كيميائية", "طاقة نووية"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/طاقة_حركية
  { category: "الفيزياء", q: "ما هي القوة التي تقاوم انزلاق الأجسام فوق بعضها وتجعل السيارات تتوقف عند الفرملة؟", a: "الاحتكاك", choices: ["الجاذبية", "الاحتكاك", "المغناطيسية", "الشد"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/احتكاك
  { category: "الفيزياء", q: "ما هي وحدة قياس الاستطاعة (القدرة) الكهربائية والتي نجدها مكتوبة على المصابيح؟", a: "الواط", choices: ["الأوم", "الفولت", "الواط", "الكولوم"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/واط
  { category: "الفيزياء", q: "ماذا تسمى الأداة التي تحتوي على إبرة مغناطيسية تشير دائماً لجهة الشمال؟", a: "البوصلة", choices: ["الرادار", "البارومتر", "الأسطرلاب", "البوصلة"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/بوصلة
  { category: "الفيزياء", q: "ماذا يحدث لوزن رائد الفضاء عندما يهبط على سطح القمر؟", a: "يقل (بسبب ضعف الجاذبية)", choices: ["يزداد", "يقل (بسبب ضعف الجاذبية)", "يبقى كما هو تماماً", "ينعدم ليصبح صفراً"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/جاذبية_القمر
  { category: "الفيزياء", q: "ما هي الوحدة المستخدمة لقياس شدة التيار الكهربائي؟", a: "الأمبير", choices: ["الفولت", "الأمبير", "الواط", "الأوم"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/أمبير
  { category: "الفيزياء", q: "ما هي العدسة التي تجمع أشعة الشمس في نقطة واحدة لتوليد حرارة عالية؟", a: "العدسة المحدبة", choices: ["العدسة المقعرة", "العدسة المستوية", "العدسة الأسطوانية", "العدسة المحدبة"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/عدسة_محدبة
  { category: "الفيزياء", q: "أي نوع من المرايا يُستخدم في جوانب السيارات لرؤية الطريق خلف السائق وتصغير الصورة؟", a: "مرآة محدبة", choices: ["مرآة مقعرة", "مرآة مستوية", "مرآة محدبة", "مرآة أسطوانية"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/مرآة_محدبة
  { category: "الفيزياء", q: "ماذا تسمى العملية التي يتحول فيها الغاز إلى سائل (مثل قطرات الندى في الصباح)؟", a: "التكثف", choices: ["التبخر", "التكثف", "الانصهار", "التسامي"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/تكثف
  { category: "الفيزياء", q: "ما هو نوع الطاقة المخزنة داخل بطارية الهاتف أو السيارة؟", a: "طاقة كيميائية", choices: ["طاقة حرارية", "طاقة كيميائية", "طاقة كهربائية", "طاقة حركية"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/طاقة_كيميائية
  { category: "الفيزياء", q: "من هو العالم الذي صاغ قوانين الحركة الثلاثة وقانون الجذب العام؟", a: "إسحاق نيوتن", choices: ["ألبرت أينشتاين", "إسحاق نيوتن", "غاليليو غاليلي", "يوهانس كبلر"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/إسحاق_نيوتن
  { category: "الفيزياء", q: "أي من المعادن التالية يعتبر أفضل وأجود موصل للكهرباء على الإطلاق؟", a: "الفضة", choices: ["النحاس", "الحديد", "الفضة", "الألمنيوم"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/موصلية_كهربائية
  { category: "الفيزياء", q: "ماذا ينتج عن دمج جميع ألوان الطيف المرئي معاً؟", a: "اللون الأبيض", choices: ["اللون الأسود", "اللون الأبيض", "اللون الرمادي", "اللون البني"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/ضوء_أبيض
  { category: "الفيزياء", q: "ما هي أسرع وسيلة لانتقال طاقة حرارة الشمس عبر الفراغ إلينا؟", a: "الإشعاع", choices: ["التوصيل", "الحمل", "الإشعاع", "الاحتكاك"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/إشعاع_حراري
  { category: "الفيزياء", q: "ماذا يسمى مسار التيار الكهربائي المغلق الذي يسمح بإضاءة المصباح؟", a: "الدائرة الكهربائية", choices: ["المجال المغناطيسي", "الشبكة", "الدائرة الكهربائية", "المقاومة"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/دائرة_كهربائية
  { category: "الفيزياء", q: "كم تبلغ سرعة الضوء في الفراغ تقريباً؟", a: "300,000 كم/ث", choices: ["150,000 كم/ث", "300,000 كم/ث", "30,000 كم/ث", "3,000 كم/ث"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/سرعة_الضوء
  { category: "الفيزياء", q: "ما هي الوحدة التي يقاس بها تردد الموجات (مثل موجات الراديو)؟", a: "الهيرتز", choices: ["المتر", "الثانية", "الهيرتز", "الواط"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/هيرتز
  { category: "الفيزياء", q: "ما هي الوحدة الدولية لقياس الشحنة الكهربائية؟", a: "كولوم", choices: ["أمبير", "فولت", "كولوم", "أوم"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/كولوم
  { category: "الفيزياء", q: "ما هي الظاهرة التي تسبب انحناء الضوء عند انتقاله من الهواء إلى الماء؟", a: "الانكسار", choices: ["الانعكاس", "الحيود", "الانكسار", "الاستقطاب"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/انكسار_(فيزياء)
  { category: "الفيزياء", q: "ما هي وحدة قياس الضغط في النظام الدولي للوحدات؟", a: "باسكال", choices: ["نيوتن", "باسكال", "جول", "واط"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/باسكال_(وحدة)
  { category: "الفيزياء", q: "ما هو المبدأ الذي ينص على أن الجسم الساكن يبقى ساكناً ما لم تؤثر عليه قوة خارجية؟", a: "القصور الذاتي", choices: ["الجاذبية", "الاحتكاك", "القصور الذاتي", "الديناميكا الحرارية"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/قصور_ذاتي
  { category: "الفيزياء", q: "ما هي الوحدة المستخدمة لقياس المقاومة الكهربائية؟", a: "الأوم", choices: ["الفولت", "الأمبير", "الأوم", "الكولوم"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/أوم
  { category: "الفيزياء", q: "ماذا يسمى الجهاز المخصص لتسجيل وقياس شدة الزلازل؟", a: "السيسموغراف", choices: ["البارومتر", "الرادار", "السيسموغراف", "الأنيمومتر"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/مقياس_الزلازل
  { category: "الفيزياء", q: "أي ألوان الطيف المرئي يمتلك أطول طول موجي وأقل تردد؟", a: "الأحمر", choices: ["البنفسجي", "الأزرق", "الأخضر", "الأحمر"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/طيف_مرئي
  { category: "الفيزياء", q: "أي ألوان الطيف المرئي يمتلك أقصر طول موجي وأعلى طاقة؟", a: "البنفسجي", choices: ["الأحمر", "الأصفر", "البنفسجي", "الأخضر"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/طيف_مرئي
  { category: "الفيزياء", q: "من هو العالم العبقري الذي فسر ظاهرة التأثير الكهروضوئي وحصل بسببه على نوبل؟", a: "ألبرت أينشتاين", choices: ["ماكس بلانك", "ألبرت أينشتاين", "نيلز بور", "إسحاق نيوتن"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/تأثير_كهروضوئي
  { category: "الفيزياء", q: "ما هو المصطلح الذي يعبر عن كمية المادة في الجسم ولا يتغير بتغير المكان (عكس الوزن)؟", a: "الكتلة", choices: ["الحجم", "الكثافة", "الكتلة", "المساحة"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/كتلة
  { category: "الفيزياء", q: "ما هي الوحدة المستخدمة لقياس مستوى شدة الصوت (الضجيج)؟", a: "ديسيبل", choices: ["هيرتز", "ديسيبل", "جول", "واط"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/ديسيبل
  { category: "الفيزياء", q: "ما هو الجهاز المستخدم لقياس الضغط الجوي للتنبؤ بحالة الطقس؟", a: "البارومتر", choices: ["الترمومتر", "البارومتر", "الأنيمومتر", "السيسموغراف"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/بارومتر
  { category: "الفيزياء", q: "ما هي الوحدة الأساسية للطاقة والعمل الميكانيكي في النظام الدولي؟", a: "الجول", choices: ["الواط", "الجول", "السعر", "الإلكترون فولت"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/جول
  { category: "الفيزياء", q: "ماذا تسمى الموجات التي تنقل الصوت والزلازل وتحتاج لوسط مادي لانتقالها؟", a: "موجات ميكانيكية", choices: ["موجات كهرومغناطيسية", "موجات ميكانيكية", "موجات إشعاعية", "أشعة غاما"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/موجة_ميكانيكية
  { category: "الفيزياء", q: "ما هي الحالة الرابعة للمادة التي تتواجد في النجوم، والشمس، والبرق؟", a: "البلازما", choices: ["الغازية", "البلازما", "الصلبة", "الميوعة"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/بلازما_(فيزياء)
  { category: "الفيزياء", q: "ماذا يحدث للمواد المعدنية بشكل عام عندما تتمدد بفعل الحرارة؟", a: "تزداد المسافات بين جزيئاتها", choices: ["تزداد كتلتها", "تزداد المسافات بين جزيئاتها", "يقل حجمها", "تزيد كثافتها"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/تمدد_حراري
  { category: "الفيزياء", q: "ما هو نوع الموجات التي تستخدمها أجهزة المايكروويف والرادار للاتصال؟", a: "موجات الراديو والمايكروويف", choices: ["موجات فوق صوتية", "موجات الراديو والمايكروويف", "أشعة غاما", "أشعة إكس"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/موجات_صغرية
  { category: "الفيزياء", q: "ما هي أصغر وحدة بناء للمادة والتي تحتفظ بجميع خصائصها الكيميائية؟", a: "الذرة", choices: ["الجزيء", "الذرة", "الإلكترون", "الكوارك"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/ذرة
  { category: "الفيزياء", q: "ماذا تسمى ظاهرة تغير تردد الموجة الصوتية عندما يقترب أو يبتعد المصدر (مثل صوت سيارة الإسعاف)؟", a: "تأثير دوبلر", choices: ["تأثير فاراداي", "تأثير دوبلر", "تأثير تيندل", "تأثير كهرومغناطيسي"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/تأثير_دوبلر
  { category: "الفيزياء", q: "من هو العالم العربي الفذ الملقب بمؤسس علم البصريات الحديث؟", a: "ابن الهيثم", choices: ["الخوارزمي", "ابن الهيثم", "الجزري", "ابن سينا"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/ابن_الهيثم
  { category: "الفيزياء", q: "ما هي الأشعة الكهرومغناطيسية التي تستخدم في المستشفيات لتصوير العظام؟", a: "الأشعة السينية (أشعة إكس)", choices: ["الأشعة تحت الحمراء", "الأشعة فوق البنفسجية", "الأشعة السينية (أشعة إكس)", "أشعة غاما"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/أشعة_سينية
  { category: "الفيزياء", q: "ماذا تسمى الطاقة المخزنة في الجسم نتيجة لارتفاعه عن سطح الأرض؟", a: "طاقة الوضع (الكامنة)", choices: ["طاقة حركية", "طاقة الوضع (الكامنة)", "طاقة حرارية", "طاقة مرنة"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/طاقة_وضع
  { category: "الفيزياء", q: "كم تبلغ سرعة الصوت في الهواء تقريباً عند درجة حرارة الغرفة الطبيعية؟", a: "343 متر/ثانية", choices: ["300 متر/ثانية", "343 متر/ثانية", "400 متر/ثانية", "500 متر/ثانية"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/سرعة_الصوت
  { category: "الفيزياء", q: "ماذا تقيس وحدة التيسلا (Tesla) في علم الفيزياء؟", a: "كثافة المجال المغناطيسي", choices: ["التيار الكهربائي المستمر", "كثافة المجال المغناطيسي", "الضغط الجوي العالي", "التردد الصوتي"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/تيسلا_(وحدة)
  { category: "الفيزياء", q: "ما هي الظاهرة التي تحدث عندما ينحني الضوء حول حافة جسم صلب أو شق ضيق؟", a: "الحيود (Diffraction)", choices: ["الانعكاس", "الانكسار", "الحيود (Diffraction)", "التشتت"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/حيود
  { category: "الفيزياء", q: "ما هي درجة الصفر المطلق التي تتوقف عندها حركة الجزيئات تقريباً، بمقياس سيلزيوس؟", a: "273.15- تحت الصفر", choices: ["100- تحت الصفر", "273.15- تحت الصفر", "360- تحت الصفر", "0 مئوية تماماً"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/صفر_مطلق
  { category: "الفيزياء", q: "ماذا تسمى المقاومة التي يبديها المائع (كالسوائل أو الغازات) ضد الجريان والانسياب؟", a: "اللزوجة", choices: ["الكثافة", "اللزوجة", "التوتر السطحي", "المرونة"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/لزوجة
  { category: "الفيزياء", q: "ما هو الغاز النبيل الذي تزداد سرعة الصوت فيه بمقدار 3 أضعاف سرعته في الهواء ويغير نبرة الصوت؟", a: "الهيليوم", choices: ["الأكسجين", "النيتروجين", "ثاني أكسيد الكربون", "الهيليوم"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/هيليوم
  { category: "الفيزياء", q: "مبدأ فيزيائي ينص على أن قوة الطفو المؤثرة على جسم تساوي وزن السائل المزاح بواسطة الجسم.. ما هو؟", a: "قاعدة أرخميدس", choices: ["قانون نيوتن الثالث", "قاعدة أرخميدس", "مبدأ برنولي", "قانون باسكال"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/قاعدة_أرخميدس
  { category: "الفيزياء", q: "ما هي الجسيمات الأولية الدقيقة التي تتكون منها البروتونات والنيوترونات في نواة الذرة؟", a: "الكواركات (Quarks)", choices: ["الإلكترونات", "الفوتونات", "الكواركات (Quarks)", "البوزيترونات"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/كوارك
  { category: "الفيزياء", q: "أي عالم صاغ المبدأ القائل بأنه يزداد ضغط المائع كلما انخفضت سرعته (أساس طيران الطائرات)؟", a: "دانييل برنولي", choices: ["بليز باسكال", "دانييل برنولي", "أرخميدس", "هاينريش هيرتز"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/مبدأ_برنولي
  { category: "الفيزياء", q: "ماذا يسمى الإشعاع الكهرومغناطيسي النظري الذي يصدر من الثقوب السوداء وتنبأ به عالم شهير؟", a: "إشعاع هوكينغ", choices: ["إشعاع شيرينكوف", "إشعاع هوكينغ", "أشعة ألفا", "تأثير كومتون"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/إشعاع_هوكينغ
  { category: "الفيزياء", q: "ما هي الحالة التي يتحول فيها الجسم من الحالة الصلبة إلى الغازية مباشرة دون المرور بالسائلة؟", a: "التسامي", choices: ["التكثف", "التبخر", "التسامي", "الترسيب"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/تسامي_(فيزياء)
  { category: "الفيزياء", q: "ما هي القوة التي تفسر الترابط القوي بين جزيئات سطح السائل مما يسمح للحشرات بالسير عليه؟", a: "التوتر السطحي", choices: ["قوة الطفو", "قوة الاحتكاك", "التوتر السطحي", "اللزوجة"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/توتر_سطحي
  { category: "الفيزياء", q: "ما هو قانون الفيزياء الذي يربط بين استطالة الزنبرك (النابض) والقوة المؤثرة عليه؟", a: "قانون هوك", choices: ["قانون أوم", "قانون هوك", "قانون باسكال", "قانون بويل"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/قانون_هوك
  { category: "الفيزياء", q: "ماذا يسمى المقياس الذي يحدد درجة العشوائية والفوضى في نظام ديناميكي حراري مغلق؟", a: "الإنتروبيا (Entropy)", choices: ["الإنثالبي (Enthalpy)", "الإنتروبيا (Entropy)", "السعة الحرارية", "الطاقة الحرة"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/إنتروبيا
  { category: "الفيزياء", q: "ما هو الجسيم عديم الكتلة تماماً والذي يمثل الكم الأساسي للضوء والإشعاع الكهرومغناطيسي؟", a: "الفوتون", choices: ["البروتون", "الإلكترون", "الفوتون", "النيوترينو"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/فوتون
  { category: "الفيزياء", q: "من هو العالم الذي اكتشف الحث الكهرومغناطيسي وهو أساس عمل المولدات والمحركات الكهربائية؟", a: "مايكل فاراداي", choices: ["نيكولا تسلا", "مايكل فاراداي", "توماس إديسون", "أندريه ماري أمبير"], difficulty: "hard", points: 200, power: false } // Source: https://ar.wikipedia.org/wiki/مايكل_فاراداي
];