export const poetryAndLiteratureQuestions = [
  { category: "شعر وأدب", q: "ماذا يسمى الشخص الذي يقوم بكتابة وتأليف القصائد؟", a: "الشاعر", choices: ["الروائي", "الشاعر", "المسرحي", "الناقد"], difficulty: "super easy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/شاعر
  { category: "شعر وأدب", q: "ما هو الفن الأدبي الذي يعتبر عكس 'الشعر' ولا يلتزم بوزن أو قافية؟", a: "النثر", choices: ["الرواية", "المسرحية", "النثر", "المقالة"], difficulty: "super easy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/نثر
  { category: "شعر وأدب", q: "ما هو المكان العام المخصص لحفظ الكتب وقراءتها واستعارتها؟", a: "المكتبة", choices: ["المتحف", "المسرح", "المكتبة", "المعرض"], difficulty: "super easy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/مكتبة
  { category: "شعر وأدب", q: "ماذا يسمى الشخص الذي يقوم بتأليف القصص الطويلة والكتب السردية؟", a: "الروائي", choices: ["الشاعر", "الروائي", "المخرج", "الممثل"], difficulty: "super easy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/روائي
  { category: "شعر وأدب", q: "ما هو العمل الأدبي المكتوب خصيصاً ليقوم الممثلون بأدائه أمام الجمهور؟", a: "المسرحية", choices: ["الرواية", "القصيدة", "المسرحية", "السيرة"], difficulty: "super easy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/مسرحية
  { category: "شعر وأدب", q: "من هو بطل المسرحية الإنجليزية الشهيرة الذي أحب 'جولييت'؟", a: "روميو", choices: ["هاملت", "عطيل", "روميو", "مكبث"], difficulty: "super easy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/روميو_وجولييت
  { category: "شعر وأدب", q: "ما هو اسم سلسلة الكتب الخيالية الشهيرة التي تتحدث عن مدرسة للسحر وفتى يحمل ندبة؟", a: "هاري بوتر", choices: ["مملكة الخواتم", "نارنيا", "هاري بوتر", "ألعاب الجوع"], difficulty: "super easy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/هاري_بوتر
  { category: "شعر وأدب", q: "ما اسم الشخصية الخيالية في أدب الأطفال التي يطول أنفها الخشبي عندما تكذب؟", a: "بينوكيو", choices: ["بيتر بان", "بينوكيو", "سندباد", "طرزان"], difficulty: "super easy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/بينوكيو
  { category: "شعر وأدب", q: "من هو الشاعر المصري الملقب بـ 'أمير الشعراء'؟", a: "أحمد شوقي", choices: ["حافظ إبراهيم", "أحمد شوقي", "طه حسين", "نجيب محفوظ"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/أحمد_شوقي
  { category: "شعر وأدب", q: "من هو الروائي العربي الوحيد الذي فاز بجائزة نوبل للآداب؟", a: "نجيب محفوظ", choices: ["توفيق الحكيم", "نجيب محفوظ", "جبران خليل جبران", "محمود درويش"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/نجيب_محفوظ
  { category: "شعر وأدب", q: "من هو شاعر فلسطين الذي كتب 'سجل أنا عربي'؟", a: "محمود درويش", choices: ["إبراهيم طوقان", "محمود درويش", "سميح القاسم", "فدوى طوقان"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/محمود_درويش
  { category: "شعر وأدب", q: "من هو الشاعر السوري الملقب بـ 'شاعر المرأة'؟", a: "نزار قباني", choices: ["أدونيس", "نزار قباني", "عمر أبو ريشة", "بدوي الجبل"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/نزار_قباني
  { category: "شعر وأدب", q: "من هو عميد الأدب العربي صاحب السيرة الذاتية 'الأيام'؟", a: "طه حسين", choices: ["العقاد", "الرافعي", "طه حسين", "المنفلوطي"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/طه_حسين
  { category: "شعر وأدب", q: "ما هي المعلقات في الأدب العربي القديم؟", a: "قصائد طويلة ممتازة", choices: ["كتب تاريخية", "قصائد طويلة ممتازة", "رسائل ملكية", "حكايات شعبية"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/المعلقات
  { category: "شعر وأدب", q: "من هو الكاتب الإنجليزي مؤلف 'روميو وجولييت' و 'هاملت'؟", a: "ويليام شكسبير", choices: ["تشارلز ديكنز", "ويليام شكسبير", "جورج أورويل", "أوسكار وايلد"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/ويليام_شكسبير
  { category: "شعر وأدب", q: "من هو الشاعر المصري الملقب بـ 'شاعر النيل'؟", a: "حافظ إبراهيم", choices: ["أحمد شوقي", "حافظ إبراهيم", "أمل دنقل", "صلاح جاهين"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/حافظ_إبراهيم
  { category: "شعر وأدب", q: "من هو مؤلف كتاب 'البخلاء' الشهير في الأدب العربي؟", a: "الجاحظ", choices: ["الأصفهاني", "المتنبي", "الجاحظ", "ابن المقفع"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/البخلاء_(كتاب)
  { category: "شعر وأدب", q: "ما اسم محبوبة الشاعر والفارس الجاهلي عنترة بن شداد؟", a: "عبلة", choices: ["ليلى", "بثينة", "عبلة", "عزة"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/عنترة_بن_شداد
  { category: "شعر وأدب", q: "من هي الروائية البريطانية التي تُلقب بـ 'ملكة الروايات البوليسية'؟", a: "أغاثا كريستي", choices: ["جين أوستن", "فرجينيا وولف", "أغاثا كريستي", "ماري شيلي"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/أجاثا_كريستي
  { category: "شعر وأدب", q: "ما اسم الرواية العالمية التي تتحدث عن مطاردة قبطان لحوت أبيض عملاق؟", a: "موبي ديك", choices: ["جزيرة الكنز", "موبي ديك", "رحلات جوليفر", "العجوز والبحر"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/موبي_ديك
  { category: "شعر وأدب", q: "ماذا يسمى التوافق الصوتي في الحروف الأخيرة من أبيات القصيدة؟", a: "القافية", choices: ["الوزن", "البحر", "القافية", "الشطر"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/قافية
  { category: "شعر وأدب", q: "ماذا يسمى البيت الأول في القصيدة العربية الكلاسيكية؟", a: "المطلع", choices: ["الخاتمة", "القافية", "المطلع", "العجز"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/مطلع_القصيدة
  { category: "شعر وأدب", q: "ماذا يسمى غرض الشعر الذي يتحدث فيه الشاعر بحزن عن شخص ميت؟", a: "الرثاء", choices: ["الهجاء", "المدح", "الرثاء", "الغزل"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/رثاء
  { category: "شعر وأدب", q: "ما هي الحكاية الخيالية التي تدور حول فتاة تفقد حذاءها الزجاجي في الحفلة؟", a: "سندريلا", choices: ["بياض الثلج", "ذات الرداء الأحمر", "سندريلا", "الأميرة النائمة"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/سندريلا
  { category: "شعر وأدب", q: "من هو مؤلف رواية 'أليس في بلاد العجائب'؟", a: "لويس كارول", choices: ["تشارلز ديكنز", "لويس كارول", "مارك توين", "هانز كريستيان أندرسن"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/أليس_في_بلاد_العجائب
  { category: "شعر وأدب", q: "من هو الشاعر الجاهلي صاحب إحدى المعلقات والملقب بـ 'الملك الضليل'؟", a: "امرؤ القيس", choices: ["زهير بن أبي سلمى", "امرؤ القيس", "طرفة بن العبد", "النابغة الذبياني"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/امرؤ_القيس
  { category: "شعر وأدب", q: "ما اسم السلسلة الروائية الشهيرة لنجيب محفوظ التي تتضمن 'بين القصرين'؟", a: "الثلاثية", choices: ["الثلاثية", "الحرافيش", "أولاد حارتنا", "اللص والكلاب"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/ثلاثية_القاهرة
  { category: "شعر وأدب", q: "في أي دولة عربية ولد وعاش الشاعر محمود درويش؟", a: "فلسطين", choices: ["سوريا", "لبنان", "فلسطين", "الأردن"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/محمود_درويش
  { category: "شعر وأدب", q: "من هو الكاتب الأمريكي الحائز على نوبل ومؤلف رواية 'العجوز والبحر'؟", a: "إرنست همينغوي", choices: ["مارك توين", "إرنست همينغوي", "إدغار آلان بو", "سكوت فيتزجيرالد"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/الشيخ_والبحر
  { category: "شعر وأدب", q: "ما هي المدينة التي كانت تعتبر عاصمة الثقافة والأدب في الأندلس؟", a: "قرطبة", choices: ["مدريد", "إشبيلية", "قرطبة", "غرناطة"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/قرطبة
  { category: "شعر وأدب", q: "من هو بطل رواية 'البؤساء' الذي سُجن بسبب سرقة رغيف خبز؟", a: "جان فالجان", choices: ["ماريوس", "جافير", "كوزيت", "جان فالجان"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/جان_فالجان
  { category: "شعر وأدب", q: "من هو الشاعر العباسي الفذ صاحب بيت: الخيل والليل والبيداء تعرفني؟", a: "المتنبي", choices: ["أبو تمام", "البحتري", "المتنبي", "أبو العلاء المعري"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/المتنبي
  { category: "شعر وأدب", q: "من هو مؤلف كتاب 'كليلة ودمنة' الشهير الذي تُرجم عن الفارسية؟", a: "عبد الله بن المقفع", choices: ["الجاحظ", "ابن خلدون", "عبد الله بن المقفع", "الأصمعي"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/كليلة_ودمنة
  { category: "شعر وأدب", q: "ما اسم العلم الذي يبحث في أوزان الشعر وقوافيه وابتكره الفراهيدي؟", a: "علم العروض", choices: ["علم البلاغة", "علم النحو", "علم العروض", "علم الصرف"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/علم_العروض
  { category: "شعر وأدب", q: "من هو مؤلف رواية 'البؤساء' العالمية؟", a: "فيكتور هوغو", choices: ["ليو تولستوي", "فيكتور هوغو", "ديستويفسكي", "بلزاك"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/البؤساء
  { category: "شعر وأدب", q: "من هو العالم الاجتماعي ومؤلف 'المقدمة' الشهيرة؟", a: "ابن خلدون", choices: ["ابن بطوطة", "ابن خلدون", "الإدريسي", "المقريزي"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/مقدمة_ابن_خلدون
  { category: "شعر وأدب", q: "من هو الشاعر الكويتي الذي كتب الملحمة الشعرية الشهيرة 'مذكرات بحار'؟", a: "محمد الفايز", choices: ["بدر بورسلي", "فائق عبد الجليل", "محمد الفايز", "أحمد العدواني"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/محمد_الفايز
  { category: "شعر وأدب", q: "من هو الشاعر العراقي رائد الشعر الحر وصاحب قصيدة 'أنشودة المطر'؟", a: "بدر شاكر السياب", choices: ["عبد الوهاب البياتي", "بدر شاكر السياب", "مظفر النواب", "نازك الملائكة"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/بدر_شاكر_السياب
  { category: "شعر وأدب", q: "من هو الروائي الكويتي الحائز على البوكر عن رواية 'ساق البامبو'؟", a: "سعود السنعوسي", choices: ["سعود السنعوسي", "طالب الرفاعي", "عبد الوهاب الحمادي", "إسماعيل فهد إسماعيل"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/ساق_البامبو_(رواية)
  { category: "شعر وأدب", q: "ما اسم الرواية المصرية الشهيرة التي ألفها 'يوسف إدريس' وتدور أحداثها في الريف؟", a: "الحرام", choices: ["الأرض", "الحرام", "زينب", "دعاء الكروان"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/الحرام_(رواية)
  { category: "شعر وأدب", q: "من هو الشاعر اللبناني الذي عاش في المهجر وصاحب كتاب 'النبي'؟", a: "جبران خليل جبران", choices: ["ميخائيل نعيمة", "إيليا أبو ماضي", "جبران خليل جبران", "أمين الريحاني"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/النبي_(كتاب)
  { category: "شعر وأدب", q: "ما اسم الملحمة العراقية القديمة التي تعتبر من أقدم القصص الأدبية في التاريخ؟", a: "ملحمة جلجامش", choices: ["ملحمة الإلياذة", "ملحمة جلجامش", "ملحمة المهابهاراتا", "ملحمة الأوديسة"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/ملحمة_جلجامش
  { category: "شعر وأدب", q: "من هو الكاتب الكولومبي الحائز على نوبل صاحب رواية 'مائة عام من العزلة'؟", a: "غابرييل غارثيا ماركيث", choices: ["خورخي بورخيس", "إيزابيل أليندي", "غابرييل غارثيا ماركيث", "ماريو فارغاس يوسا"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/مئة_عام_من_العزلة
  { category: "شعر وأدب", q: "من هو الكاتب الإسباني مؤلف رواية الفروسية الشهيرة 'دون كيشوت'؟", a: "ميغيل دي ثيربانتس", choices: ["فيكتور هوغو", "ميغيل دي ثيربانتس", "دانتي", "هوميروس"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/دون_كيشوت
  { category: "شعر وأدب", q: "بأي غرض شعري اشتهر الشاعر العباسي 'أبو العتاهية'؟", a: "الزهد", choices: ["المدح", "الغزل", "الرثاء", "الزهد"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/أبو_العتاهية
  { category: "شعر وأدب", q: "من هو الشاعر اللبناني الذي أُطلق عليه لقب 'شاعر القطرين' (مصر والشام)؟", a: "خليل مطران", choices: ["أحمد شوقي", "إيليا أبو ماضي", "خليل مطران", "حافظ إبراهيم"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/خليل_مطران
  { category: "شعر وأدب", q: "من هو المؤلف الفذ لمعجم 'لسان العرب'، أشهر معاجم اللغة العربية؟", a: "ابن منظور", choices: ["الفراهيدي", "الجوهري", "ابن منظور", "الفيروزآبادي"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/لسان_العرب
  { category: "شعر وأدب", q: "ماذا يسمى شكل الشعر العربي الكلاسيكي المكون من صدر وعجز في كل بيت؟", a: "الشعر العمودي", choices: ["الشعر الحر", "قصيدة النثر", "الموشح", "الشعر العمودي"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/شعر_عمودي
  { category: "شعر وأدب", q: "من هي الشاعرة الجاهلية والإسلامية التي اشتهرت برثاء أخويها صخر ومعاوية؟", a: "الخنساء", choices: ["ليلى الأخيلية", "الخنساء", "ولادة بنت المستكفي", "رابعة العدوية"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/الخنساء
  { category: "شعر وأدب", q: "من هو الروائي السوداني العالمي مؤلف رواية 'موسم الهجرة إلى الشمال'؟", a: "الطيب صالح", choices: ["يوسف زيدان", "الطيب صالح", "عبد الرحمن منيف", "إبراهيم الكوني"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/موسم_الهجرة_إلى_الشمال
  { category: "شعر وأدب", q: "من هو الروائي البرازيلي المعاصر صاحب الرواية الملهمة 'الخيميائي'؟", a: "باولو كويلو", choices: ["ماركيز", "باولو كويلو", "جورج أمادو", "خورخي أمادو"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/الخيميائي_(رواية)
  { category: "شعر وأدب", q: "من هو الكاتب والروائي المصري مؤلف رواية 'في بيتنا رجل' و'أنا حرة'؟", a: "إحسان عبد القدوس", choices: ["نجيب محفوظ", "يوسف السباعي", "إحسان عبد القدوس", "طه حسين"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/إحسان_عبد_القدوس
  { category: "شعر وأدب", q: "من هو العالم الأندلسي مؤلف كتاب 'طوق الحمامة في الألفة والأُلّاف'؟", a: "ابن حزم الأندلسي", choices: ["ابن رشد", "ابن طفيل", "ابن حزم الأندلسي", "ابن زيدون"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/طوق_الحمامة
  { category: "شعر وأدب", q: "ماذا يسمى الفن الأدبي الذي يكتب فيه الشخص قصة وتفاصيل حياته بنفسه؟", a: "السيرة الذاتية", choices: ["المذكرات", "اليوميات", "السيرة الذاتية", "الرواية التاريخية"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/سيرة_ذاتية
  { category: "شعر وأدب", q: "من هو الروائي الروسي العظيم صاحب رواية 'الجريمة والعقاب' و'الأبله'؟", a: "فيودور دوستويفسكي", choices: ["ليو تولستوي", "أنطون تشيخوف", "فيودور دوستويفسكي", "مكسيم غوركي"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/فيودور_دوستويفسكي
  { category: "شعر وأدب", q: "من هو الكاتب الفرنسي الرائد في الخيال العلمي مؤلف 'حول العالم في ثمانين يوماً'؟", a: "جول فيرن", choices: ["فيكتور هوغو", "ألكسندر دوما", "جول فيرن", "ألبير كامو"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/حول_العالم_في_ثمانين_يوما
  { category: "شعر وأدب", q: "من هو الشاعر الأندلسي الذي اشتهر بقصة حبه لولادة بنت المستكفي وصاحب 'النونية'؟", a: "ابن زيدون", choices: ["المعتمد بن عباد", "ابن هانئ", "ابن خفاجة", "ابن زيدون"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/ابن_زيدون
  { category: "شعر وأدب", q: "من هي الروائية الإنجليزية الكلاسيكية مؤلفة رواية 'كبرياء وتحامل'؟", a: "جين أوستن", choices: ["إيميلي برونتي", "جين أوستن", "تشارلوت برونتي", "ماري آن إيفانز"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/كبرياء_وتحامل_(رواية)
  { category: "شعر وأدب", q: "من هو الكاتب والشاعر السوري مؤلف المسرحية السياسية الساخرة 'كاسك يا وطن'؟", a: "محمد الماغوط", choices: ["دريد لحام", "سعد الله ونوس", "محمد الماغوط", "ممدوح عدوان"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/محمد_الماغوط
  { category: "شعر وأدب", q: "إلى أي مدرسة أدبية ينتمي الشاعر اللبناني إيليا أبو ماضي؟", a: "شعراء المهجر", choices: ["الديوان", "أبولو", "شعراء المهجر", "الإحياء والبعث"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/إيليا_أبو_ماضي
  { category: "شعر وأدب", q: "من هو الكاتب الإنجليزي صاحب الرواية الديستوبية الشهيرة '1984'؟", a: "جورج أورويل", choices: ["ألدوس هكسلي", "جورج أورويل", "راي برادبري", "آرثر كلارك"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/1984_(رواية)
  { category: "شعر وأدب", q: "ما اسم الرواية الخماسية التي اشتهر بها الكاتب السعودي 'عبد الرحمن منيف' وتؤرخ لتحولات النفط؟", a: "مدن الملح", choices: ["مدن الملح", "بنات الرياض", "سقف الكفاية", "الحزام"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/مدن_الملح
  { category: "شعر وأدب", q: "ما هو اللقب الذي عُرف به الشاعر السوري الكبير 'محمد سليمان الأحمد'؟", a: "بدوي الجبل", choices: ["أدونيس", "الأخطل الصغير", "بدوي الجبل", "الفرزدق"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/بدوي_الجبل
  { category: "شعر وأدب", q: "من هو الكاتب والمؤرخ العباسي صاحب كتاب 'الأغاني' الموسوعي في الأدب والتراجم؟", a: "أبو الفرج الأصفهاني", choices: ["الجاحظ", "الأصمعي", "أبو الفرج الأصفهاني", "ابن عبد ربه"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/كتاب_الأغاني
  { category: "شعر وأدب", q: "من هو الشاعر الفارس الذي يُعتبر أول من 'قصد القصائد' (أطالها) في الشعر العربي؟", a: "المهلهل بن ربيعة", choices: ["امرؤ القيس", "المهلهل بن ربيعة", "الشنفرى", "تأبط شراً"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/المهلهل_بن_ربيعة
  { category: "شعر وأدب", q: "من هو الشاعر الإيطالي الذي ألف الملحمة الشعرية الشهيرة 'الكوميديا الإلهية'؟", a: "دانتي أليغييري", choices: ["جيوفاني بوكاتشيو", "فرانسيسكو بتراركا", "دانتي أليغييري", "نيكولو مكيافيللي"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/الكوميديا_الإلهية
  { category: "شعر وأدب", q: "من هو الكاتب العراقي الفائز بجائزة البوكر العربية عن روايته 'فرانكنشتاين في بغداد'؟", a: "أحمد سعداوي", choices: ["سنان أنطون", "علي بدر", "حسن بلاسم", "أحمد سعداوي"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/فرانكنشتاين_في_بغداد
  { category: "شعر وأدب", q: "ما هو الاسم الحقيقي للشاعر اللبناني الملقب بـ 'الأخطل الصغير'؟", a: "بشارة الخوري", choices: ["سعيد عقل", "بشارة الخوري", "إيليا أبو ماضي", "خليل مطران"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/بشارة_الخوري_(شاعر)
  { category: "شعر وأدب", q: "ما هو اسم البطل الوهمي والداهية الذي تدور حوله أحداث 'مقامات الحريري'؟", a: "أبو زيد السروجي", choices: ["عيسى بن هشام", "أبو الفتح الإسكندري", "أبو زيد السروجي", "الحارث بن همام"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/مقامات_الحريري
  { category: "شعر وأدب", q: "ما هي الرواية الفرنسية التي تعتبر من أطول الروايات في التاريخ للكاتب مارسيل بروست؟", a: "البحث عن الزمن المفقود", choices: ["البحث عن الزمن المفقود", "الغريب", "الأحمر والأسود", "مادام بوفاري"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/بحثا_عن_الزمن_المفقود
  { category: "شعر وأدب", q: "من هو الفيلسوف والشاعر العباسي الذي لزم بيته ولقب نفسه بـ 'رهين المحبسين'؟", a: "أبو العلاء المعري", choices: ["ابن الرومي", "أبو نواس", "أبو العلاء المعري", "بشار بن برد"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/أبو_العلاء_المعري
  { category: "شعر وأدب", q: "أي رواية يُجمع النقاد على أنها أول رواية عربية ناضجة فنياً (نُشرت عام 1914) ولمن؟", a: "زينب لمحمد حسين هيكل", choices: ["دعاء الكروان لطه حسين", "زينب لمحمد حسين هيكل", "عودة الروح لتوفيق الحكيم", "الأيام لطه حسين"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/زينب_(رواية)
  { category: "شعر وأدب", q: "من هو الروائي والشاعر الروسي صاحب 'دكتور جيفاغو' الذي أُجبر على رفض جائزة نوبل؟", a: "بوريس باسترناك", choices: ["تولستوي", "ألكسندر بوشكين", "بوريس باسترناك", "ميخائيل شولوخوف"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/بوريس_باسترناك
  { category: "شعر وأدب", q: "من هو الروائي الليبي الملقب بـ 'رجل الصحراء' وصاحب رواية 'المجوس' العظيمة؟", a: "إبراهيم الكوني", choices: ["إبراهيم الكوني", "أحمد إبراهيم الفقيه", "هشام مطر", "الصادق النيهوم"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/إبراهيم_الكوني
  { category: "شعر وأدب", q: "من هو العالم والمفكر المعتزلي العباسي صاحب موسوعة 'كتاب الحيوان' الأدبية والعلمية؟", a: "الجاحظ", choices: ["الدميري", "القزويني", "الجاحظ", "التوحيدي"], difficulty: "hard", points: 200, power: false } // Source: https://ar.wikipedia.org/wiki/كتاب_الحيوان
];