export const prophetsQuestions = [
  { category: "قصص الأنبياء", q: "من هو أبو البشر وأول الأنبياء؟", a: "آدم عليه السلام", choices: ["نوح عليه السلام", "إدريس عليه السلام", "آدم عليه السلام", "إبراهيم عليه السلام"], difficulty: "supereasy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/آدم
  { category: "قصص الأنبياء", q: "من هو خاتم الأنبياء والمرسلين؟", a: "محمد ﷺ", choices: ["موسى عليه السلام", "محمد ﷺ", "عيسى عليه السلام", "إبراهيم عليه السلام"], difficulty: "supereasy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/محمد
  { category: "قصص الأنبياء", q: "من هو النبي الذي بنى السفينة العظيمة لتنجيته ومن آمن معه من الطوفان؟", a: "نوح عليه السلام", choices: ["إبراهيم عليه السلام", "موسى عليه السلام", "نوح عليه السلام", "يونس عليه السلام"], difficulty: "supereasy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/نوح
  { category: "قصص الأنبياء", q: "في أي مدينة مباركة وُلد النبي محمد ﷺ؟", a: "مكة المكرمة", choices: ["المدينة المنورة", "الطائف", "مكة المكرمة", "القدس"], difficulty: "supereasy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/محمد
  { category: "قصص الأنبياء", q: "ما اسم النبي الذي التقمه الحوت وهو في البحر؟", a: "يونس عليه السلام", choices: ["لوط عليه السلام", "يونس عليه السلام", "أيوب عليه السلام", "هود عليه السلام"], difficulty: "supereasy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/يونس
  { category: "قصص الأنبياء", q: "من هو النبي الذي أُلقي في النار فجعلها الله برداً وسلاماً عليه؟", a: "إبراهيم عليه السلام", choices: ["موسى عليه السلام", "نوح عليه السلام", "إبراهيم عليه السلام", "لوط عليه السلام"], difficulty: "supereasy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/إبراهيم
  { category: "قصص الأنبياء", q: "من هي المرأة الأولى التي خلقها الله لتكون زوجة لآدم عليه السلام؟", a: "حواء", choices: ["سارة", "حواء", "هاجر", "آسية"], difficulty: "supereasy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/حواء
  { category: "قصص الأنبياء", q: "ما هي المعجزة التي أيّد الله بها نبيه موسى عليه السلام عندما ألقاها على الأرض؟", a: "العصا التي تحولت لثعبان", choices: ["الناقة", "إحياء الموتى", "العصا التي تحولت لثعبان", "انشقاق القمر"], difficulty: "supereasy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/موسى
  { category: "قصص الأنبياء", q: "من هو النبي الذي تكلم في المهد وهو لا يزال رضيعاً؟", a: "عيسى عليه السلام", choices: ["يحيى عليه السلام", "عيسى عليه السلام", "موسى عليه السلام", "إسماعيل عليه السلام"], difficulty: "supereasy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/عيسى_بن_مريم
  { category: "قصص الأنبياء", q: "من هو النبي الذي كان يفهم لغة الحيوانات والطيور والنمل؟", a: "سليمان عليه السلام", choices: ["داود عليه السلام", "سليمان عليه السلام", "أيوب عليه السلام", "يوسف عليه السلام"], difficulty: "supereasy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/سليمان
  { category: "قصص الأنبياء", q: "من هو النبي الذي أمره الله ببناء الكعبة المشرفة مع ابنه؟", a: "إبراهيم عليه السلام", choices: ["نوح عليه السلام", "موسى عليه السلام", "محمد ﷺ", "إبراهيم عليه السلام"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/الكعبة
  { category: "قصص الأنبياء", q: "من هو الابن الذي عاون إبراهيم عليه السلام في رفع قواعد الكعبة؟", a: "إسماعيل عليه السلام", choices: ["إسحاق عليه السلام", "يعقوب عليه السلام", "إسماعيل عليه السلام", "يوسف عليه السلام"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/إسماعيل
  { category: "قصص الأنبياء", q: "ما هو اللقب العظيم الذي أُطلق على إبراهيم عليه السلام؟", a: "خليل الله", choices: ["كليم الله", "خليل الله", "ذو النون", "روح الله"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/إبراهيم
  { category: "قصص الأنبياء", q: "ما هو اللقب العظيم الذي أُطلق على موسى عليه السلام؟", a: "كليم الله", choices: ["خليل الله", "روح الله", "كليم الله", "حبيب الله"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/موسى
  { category: "قصص الأنبياء", q: "من هو النبي الذي ضُرب به المثل في الصبر على المرض وفقدان الأهل والمال؟", a: "أيوب عليه السلام", choices: ["أيوب عليه السلام", "يونس عليه السلام", "شعيب عليه السلام", "لوط عليه السلام"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/أيوب
  { category: "قصص الأنبياء", q: "إلى أي قوم أُرسل هود عليه السلام؟", a: "عاد", choices: ["ثمود", "مدين", "عاد", "بنو إسرائيل"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/هود
  { category: "قصص الأنبياء", q: "إلى أي قوم أُرسل صالح عليه السلام؟", a: "ثمود", choices: ["عاد", "ثمود", "مدين", "فرعون"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/صالح
  { category: "قصص الأنبياء", q: "إلى أي قوم أُرسل شعيب عليه السلام؟", a: "مدين", choices: ["عاد", "مدين", "ثمود", "بنو إسرائيل"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/شعيب
  { category: "قصص الأنبياء", q: "ما هي المعجزة الشهيرة المرتبطة بنبي الله صالح عليه السلام؟", a: "الناقة", choices: ["العصا", "الناقة", "إحياء الموتى", "الفلك"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/صالح
  { category: "قصص الأنبياء", q: "من هو أخو موسى عليه السلام الذي أرسله الله معه وزيراً ومُعيناً؟", a: "هارون عليه السلام", choices: ["داود عليه السلام", "هارون عليه السلام", "شعيب عليه السلام", "زكريا عليه السلام"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/هارون
  { category: "قصص الأنبياء", q: "من هي السيدة العظيمة والدة عيسى عليه السلام؟", a: "مريم", choices: ["آسية", "مريم", "هاجر", "سارة"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/مريم_العذراء
  { category: "قصص الأنبياء", q: "من هو النبي الذي آتاه الله جمالاً شديداً وعلمه تفسير الأحلام؟", a: "يوسف عليه السلام", choices: ["يونس عليه السلام", "يوسف عليه السلام", "هارون عليه السلام", "إلياس عليه السلام"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/يوسف
  { category: "قصص الأنبياء", q: "من هو النبي الذي ألان الله له الحديد فصنع منه الدروع؟", a: "داود عليه السلام", choices: ["سليمان عليه السلام", "داود عليه السلام", "إدريس عليه السلام", "موسى عليه السلام"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/داود
  { category: "قصص الأنبياء", q: "من هو النبي الذي أُرسل إلى قوم اشتهروا بالفاحشة التي لم يسبقهم بها أحد؟", a: "لوط عليه السلام", choices: ["إلياس عليه السلام", "لوط عليه السلام", "شعيب عليه السلام", "صالح عليه السلام"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/لوط
  { category: "قصص الأنبياء", q: "ما اسم البحر الذي فلقه الله لموسى وقومه لينجيهم من فرعون وجنوده؟", a: "البحر الأحمر", choices: ["البحر الأحمر", "بحر قزوين", "البحر الأسود", "البحر المتوسط"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/موسى
  { category: "قصص الأنبياء", q: "ما هو اللقب الذي عُرف به النبي محمد ﷺ بين قريش قبل البعثة؟", a: "الصادق الأمين", choices: ["الفاروق", "الصادق الأمين", "ذو النون", "سيف الله"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/محمد
  { category: "قصص الأنبياء", q: "ما اسم والدة النبي محمد ﷺ؟", a: "آمنة بنت وهب", choices: ["حليمة السعدية", "خديجة بنت خويلد", "آمنة بنت وهب", "فاطمة بنت أسد"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/آمنة_بنت_وهب
  { category: "قصص الأنبياء", q: "كم كان عمر النبي محمد ﷺ عندما نزل عليه الوحي لأول مرة؟", a: "40 سنة", choices: ["25 سنة", "33 سنة", "40 سنة", "50 سنة"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/محمد
  { category: "قصص الأنبياء", q: "من هو النبي الذي لُقب بـ 'أبي الأنبياء' لأن الرسل من بعده من نسله؟", a: "إبراهيم عليه السلام", choices: ["آدم عليه السلام", "نوح عليه السلام", "إبراهيم عليه السلام", "موسى عليه السلام"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/إبراهيم
  { category: "قصص الأنبياء", q: "ما هي المعجزة التي تحدى بها إبراهيم عليه السلام قومه وملكهم النمرود؟", a: "عدم احتراقه بالنار", choices: ["تحويل العصا", "إحياء الموتى", "عدم احتراقه بالنار", "شق البحر"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/إبراهيم
  { category: "قصص الأنبياء", q: "ما اسم الجبل الذي صعد عليه موسى ليكلم ربه؟", a: "طور سيناء", choices: ["جبل النور", "جبل أحد", "طور سيناء", "جبل الجودي"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/جبل_موسى_(مصر)
  { category: "قصص الأنبياء", q: "من هو النبي الذي بكى على فراق ابنه حتى فقد بصره؟", a: "يعقوب عليه السلام", choices: ["إسماعيل عليه السلام", "يوسف عليه السلام", "يعقوب عليه السلام", "هارون عليه السلام"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/يعقوب
  { category: "قصص الأنبياء", q: "ما هو الحيوان الذي زعم إخوة يوسف كذباً أنه أكل أخاهم؟", a: "الذئب", choices: ["الأسد", "النمر", "الذئب", "الضبع"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/يوسف
  { category: "قصص الأنبياء", q: "ما هي العصا التي انقلبت ثعباناً مبيناً بأمر الله؟", a: "عصا موسى", choices: ["عصا هارون", "عصا موسى", "عصا سليمان", "عصا شعيب"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/موسى
  { category: "قصص الأنبياء", q: "من هي الزوجة الأولى لإبراهيم عليه السلام وأم إسحاق؟", a: "سارة", choices: ["هاجر", "مريم", "سارة", "آسية"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/سارة
  { category: "قصص الأنبياء", q: "من هو النبي الذي جعله الله وزيراً لأخيه موسى ليشد به أزره؟", a: "هارون عليه السلام", choices: ["موسى عليه السلام", "هارون عليه السلام", "شعيب عليه السلام", "لوط عليه السلام"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/هارون
  { category: "قصص الأنبياء", q: "من هو النبي الملقب بـ 'ذبيح الله' في قول جمهور العلماء من المسلمين؟", a: "إسماعيل عليه السلام", choices: ["إسحاق عليه السلام", "إسماعيل عليه السلام", "يحيى عليه السلام", "زكريا عليه السلام"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/إسماعيل
  { category: "قصص الأنبياء", q: "من هو النبي الذي أُنزل عليه كتاب 'الزبور'؟", a: "داود عليه السلام", choices: ["موسى عليه السلام", "داود عليه السلام", "سليمان عليه السلام", "إدريس عليه السلام"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/الزبور
  { category: "قصص الأنبياء", q: "ما هو اسم الطائر الذي تفقدّه سليمان فلم يجده ثم جاءه بخبر سبأ؟", a: "الهدهد", choices: ["الغراب", "الهدهد", "الصقر", "الحمامة"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/هدهد_سليمان
  { category: "قصص الأنبياء", q: "ما هي أطول قصة وردت كاملة ومفصلة في سورة واحدة بالقرآن الكريم؟", a: "قصة يوسف عليه السلام", choices: ["قصة موسى عليه السلام", "قصة نوح عليه السلام", "قصة يوسف عليه السلام", "قصة إبراهيم عليه السلام"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/سورة_يوسف
  { category: "قصص الأنبياء", q: "كم عدد السنين التي لبثها نوح عليه السلام يدعو قومه للإيمان؟", a: "950 سنة", choices: ["300 سنة", "700 سنة", "950 سنة", "1000 سنة"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/نوح
  { category: "قصص الأنبياء", q: "بماذا وُصف إدريس عليه السلام في القرآن الكريم؟", a: "صِدِّيقاً نبياً", choices: ["ملكاً عظيماً", "صِدِّيقاً نبياً", "صاحب الحوت", "ذا الكفل"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/إدريس
  { category: "قصص الأنبياء", q: "بماذا اشتهر قوم عاد (قوم هود) في بناء مساكنهم؟", a: "إرم ذات العماد (قصور عالية)", choices: ["نحت الجبال", "إرم ذات العماد (قصور عالية)", "الخيام المتنقلة", "السفن العملاقة"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/إرم_ذات_العماد
  { category: "قصص الأنبياء", q: "ما هو اللقب القرآني الذي أُطلق على النبي يونس عليه السلام؟", a: "ذو النون", choices: ["ذو الكفل", "ذو القرنين", "ذو النون", "روح الله"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/يونس
  { category: "قصص الأنبياء", q: "من هو النبي الذي سأل ربه أن يرزقه ولداً وهو في سن متأخرة فبُشّر بيحيى؟", a: "زكريا عليه السلام", choices: ["عمران", "زكريا عليه السلام", "يعقوب عليه السلام", "هارون عليه السلام"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/زكريا
  { category: "قصص الأنبياء", q: "من هو النبي الذي وصفه الله بأنه 'سيداً وحصوراً ونبياً من الصالحين'؟", a: "يحيى عليه السلام", choices: ["يحيى عليه السلام", "هارون عليه السلام", "أيوب عليه السلام", "هود عليه السلام"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/يحيى
  { category: "قصص الأنبياء", q: "ما هو الاسم الآخر الذي يُعرف به يعقوب عليه السلام؟", a: "إسرائيل", choices: ["إسرائيل", "إسرافيل", "إلياس", "عزرائيل"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/يعقوب
  { category: "قصص الأنبياء", q: "من هو شقيق يوسف عليه السلام من أمه وأبيه؟", a: "بنيامين", choices: ["روبين", "يهوذا", "شمعون", "بنيامين"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/بنيامين
  { category: "قصص الأنبياء", q: "كم كوكباً رآه يوسف عليه السلام ساجداً له في رؤياه مع الشمس والقمر؟", a: "11 كوكباً", choices: ["7 كواكب", "9 كواكب", "11 كوكباً", "12 كوكباً"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/يوسف
  { category: "قصص الأنبياء", q: "بماذا اشتهر قوم شعيب (أهل مدين) من فساد في المعاملات؟", a: "التطفيف في الميزان", choices: ["عبادة النار", "التطفيف في الميزان", "السحر والشعوذة", "سرقة القوافل"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/مدين
  { category: "قصص الأنبياء", q: "من هو الجبار الذي قتله داود عليه السلام وكان سبباً في بروزه كقائد؟", a: "جالوت", choices: ["النمرود", "جالوت", "فرعون", "هامان"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/جالوت
  { category: "قصص الأنبياء", q: "ما هي المهنة أو الحرفة التي كان يعمل بها نبي الله داود لكسب رزقه؟", a: "صناعة الدروع", choices: ["النجارة", "صناعة الدروع", "الزراعة", "رعي الأغنام"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/داود
  { category: "قصص الأنبياء", q: "ما هي الدابة التي أكلت 'منسأة' (عصا) سليمان ليعلم الجن بموته؟", a: "دابة الأرض (الأرضة)", choices: ["النملة", "الهدهد", "دابة الأرض (الأرضة)", "الجمل"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/سليمان
  { category: "قصص الأنبياء", q: "من هو النبي الذي سأل الله أن يُريه كيف يحيي الموتى ليطمئن قلبه؟", a: "إبراهيم عليه السلام", choices: ["موسى عليه السلام", "إبراهيم عليه السلام", "عيسى عليه السلام", "عزير عليه السلام"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/إبراهيم
  { category: "قصص الأنبياء", q: "ما اسم المكان أو الوادي الذي كلّم الله فيه موسى لأول مرة؟", a: "الوادي المقدس طوى", choices: ["وادي محسر", "الوادي المقدس طوى", "غار حراء", "وادي النمل"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/طوى
  { category: "قصص الأنبياء", q: "من هو النبي الذي بشّر برسول يأتي من بعده اسمه 'أحمد'؟", a: "عيسى عليه السلام", choices: ["يحيى عليه السلام", "موسى عليه السلام", "عيسى عليه السلام", "إبراهيم عليه السلام"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/عيسى_بن_مريم
  { category: "قصص الأنبياء", q: "من هو النبي الذي كان صوته أعذب الأصوات في قراءة الزبور؟", a: "داود عليه السلام", choices: ["يوسف عليه السلام", "محمد ﷺ", "داود عليه السلام", "يحيى عليه السلام"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/داود
  { category: "قصص الأنبياء", q: "ما صلة القرابة بين النبي لوط والنبي إبراهيم عليهما السلام؟", a: "ابن أخيه", choices: ["ابنه", "أخوه", "ابن أخيه", "والده"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/لوط
  { category: "قصص الأنبياء", q: "من هو النبي الذي سخر الله له الجبال تسبح معه بالعشي والإشراق؟", a: "داود عليه السلام", choices: ["سليمان عليه السلام", "داود عليه السلام", "موسى عليه السلام", "نوح عليه السلام"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/داود
  { category: "قصص الأنبياء", q: "من هو الرجل الصالح العالِم الذي رحل إليه موسى ليتعلم منه؟", a: "الخضر", choices: ["لقمان الحكيم", "الخضر", "ذو القرنين", "يوشع بن نون"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/الخضر
  { category: "قصص الأنبياء", q: "ما هي المعجزة الثانية لموسى (غير العصا) التي أظهرها لفرعون؟", a: "يده تخرج بيضاء", choices: ["شق القمر", "إحياء الموتى", "يده تخرج بيضاء", "تفتيت الجبال"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/موسى
  { category: "قصص الأنبياء", q: "ما اسم القرية أو المدينة التي أُرسل إليها لوط عليه السلام؟", a: "سدوم", choices: ["نينوى", "سدوم", "أنطاكية", "بابل"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/سدوم
  { category: "قصص الأنبياء", q: "ما هو القميص الذي ألقوه على وجه يعقوب فارتد بصيراً؟", a: "قميص يوسف", choices: ["قميص إبراهيم", "قميص يوسف", "رداء الملائكة", "قميص بنيامين"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/يعقوب
  { category: "قصص الأنبياء", q: "ما اسم الشجرة التي أنبتها الله فوق يونس عليه السلام بعد خروجه من بطن الحوت لتقيه حر الشمس؟", a: "شجرة من يقطين", choices: ["شجرة زيتون", "شجرة تين", "شجرة من يقطين", "شجرة سدر"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/يونس
  { category: "قصص الأنبياء", q: "من هو النبي الذي كان يبرئ الأكمه (الأعمى) والأبرص بإذن الله؟", a: "عيسى عليه السلام", choices: ["يحيى عليه السلام", "عيسى عليه السلام", "أيوب عليه السلام", "إبراهيم عليه السلام"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/عيسى_بن_مريم
  { category: "قصص الأنبياء", q: "ما هي المهنة الأولى التي عمل بها نبي الله آدم عليه السلام على الأرض؟", a: "الزراعة (الحراثة)", choices: ["النجارة", "الحدادة", "الزراعة (الحراثة)", "الرعي"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/آدم
  { category: "قصص الأنبياء", q: "من الذي بعثه الله ليعلم قابيل كيف يواري سوأة أخيه هابيل؟", a: "غراب", choices: ["حمامة", "غراب", "كلب", "ذئب"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/قابيل_وهابيل
  { category: "قصص الأنبياء", q: "ما هو لقب النبي نوح عليه السلام لكثرة الأنبياء من نسله؟", a: "أبو البشر الثاني", choices: ["خليل الله", "أبو البشر الثاني", "كليم الله", "ذو النون"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/نوح
  { category: "قصص الأنبياء", q: "أين تقع المنطقة التي يُعتقد أن سفينة نوح عليه السلام استقرت عليها (جبل الجودي)؟", a: "جنوب شرق تركيا", choices: ["مصر", "جنوب شرق تركيا", "اليمن", "المغرب"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/جبل_الجودي
  { category: "قصص الأنبياء", q: "من هو النبي الذي خصه الله بأنه 'لُقب بخطيب الأنبياء' لفصاحته وحسن مراجعته لقومه؟", a: "شعيب عليه السلام", choices: ["صالح عليه السلام", "هود عليه السلام", "شعيب عليه السلام", "إسماعيل عليه السلام"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/شعيب
  { category: "قصص الأنبياء", q: "ما هي المدينة التي يُعتقد أن النبي يونس عليه السلام أرسل إلى أهلها؟", a: "نينوى (بالعراق)", choices: ["بابل", "نينوى (بالعراق)", "دمشق", "القدس"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/نينوى
  { category: "قصص الأنبياء", q: "ما هو الكائن الذي نفخ في النار ليوقدها على إبراهيم، ولذلك أُمرنا بقتله؟", a: "الوزغ (البرص)", choices: ["الثعبان", "الوزغ (البرص)", "العقرب", "الفأر"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/وزغ
  { category: "قصص الأنبياء", q: "من هو الوزير المخلص لفرعون والذي تكبر معه وأمره ببناء الصرح؟", a: "هامان", choices: ["قارون", "السامري", "هامان", "أبرهة"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/هامان
  { category: "قصص الأنبياء", q: "من هو الرجل الذي كان من قوم موسى وبغى عليهم بثرائه الفاحش ومفاتيحه الثقيلة؟", a: "قارون", choices: ["هامان", "السامري", "قارون", "فرعون"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/قارون
  { category: "قصص الأنبياء", q: "ما اسم النبي الذي رُفع إلى السماء وهو حي وسينزل في آخر الزمان؟", a: "عيسى عليه السلام", choices: ["إدريس عليه السلام", "إلياس عليه السلام", "عيسى عليه السلام", "يحيى عليه السلام"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/عيسى_بن_مريم
  { category: "قصص الأنبياء", q: "بماذا عاقب الله قوم هود (عاد) لرفضهم الإيمان؟", a: "بريح صرصر عاتية", choices: ["بالغرق", "بالصيحة", "بريح صرصر عاتية", "بالخسف"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/عاد
  { category: "قصص الأنبياء", q: "بماذا عاقب الله قوم صالح (ثمود) بعد أن عقروا الناقة؟", a: "بالصيحة والرجفة", choices: ["بالغرق", "بالصيحة والرجفة", "بريح صرصر", "بوابل من الحجارة"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/ثمود
  { category: "قصص الأنبياء", q: "من هي زوجة فرعون المؤمنة التي ضرب الله بها مثلاً للذين آمنوا؟", a: "آسية بنت مزاحم", choices: ["مريم بنت عمران", "آسية بنت مزاحم", "هاجر", "بلقيس"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/آسية_بنت_مزاحم
  { category: "قصص الأنبياء", q: "من هو النبي الذي أتاه الله الحكم وهو صبي (كما ذكر في سورة مريم)؟", a: "يحيى عليه السلام", choices: ["يوسف عليه السلام", "إسماعيل عليه السلام", "يحيى عليه السلام", "عيسى عليه السلام"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/يحيى
  { category: "قصص الأنبياء", q: "كم يوماً صام زكريا عليه السلام عن الكلام مع الناس (إلا رمزاً) آيةً على حمل زوجته؟", a: "ثلاث ليالٍ", choices: ["سبع ليالٍ", "ثلاث ليالٍ", "عشرة أيام", "أربعين يوماً"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/زكريا
  { category: "قصص الأنبياء", q: "من هو النبي الذي يُعتقد أنه أول من خط بالقلم وخاط الثياب؟", a: "إدريس عليه السلام", choices: ["نوح عليه السلام", "إدريس عليه السلام", "شيث عليه السلام", "إبراهيم عليه السلام"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/إدريس
  { category: "قصص الأنبياء", q: "ما اسم أم موسى عليه السلام (الاسم المتداول في السير والتاريخ)؟", a: "يوكابد", choices: ["آسية", "حنة", "يوكابد", "مريم"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/يوكابد_بنت_لاوي
  { category: "قصص الأنبياء", q: "من هو الفتى الذي رافق موسى عليه السلام في رحلته للقاء الخضر، وأصبح نبياً من بعده؟", a: "يوشع بن نون", choices: ["كالب بن يوفنا", "يوشع بن نون", "هارون عليه السلام", "عزير"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/يوشع_بن_نون
  { category: "قصص الأنبياء", q: "في أي سورة ذُكرت قصة ذي القرنين وبناء السد على يأجوج ومأجوج؟", a: "سورة الكهف", choices: ["سورة البقرة", "سورة الأنبياء", "سورة الكهف", "سورة القصص"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/سورة_الكهف
  { category: "قصص الأنبياء", q: "ما هو الاسم الذي أُطلق على الملك الجبار الذي حاجّ إبراهيم في ربه؟", a: "النمرود", choices: ["فرعون", "هامان", "قارون", "النمرود"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/نمرود
  { category: "قصص الأنبياء", q: "ما هو العذاب الذي أهلك الله به جيش أبرهة الحبشي حين أراد هدم الكعبة؟", a: "طير أبابيل", choices: ["ريح صرصر", "طير أبابيل", "خسف الأرض", "صيحة قوية"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/عام_الفيل
  { category: "قصص الأنبياء", q: "ما اسم النبي الذي أماته الله مائة عام ثم بعثه ليريه كيف يحيي الموتى؟", a: "عزير", choices: ["إلياس عليه السلام", "اليسع عليه السلام", "عزير", "يوشع بن نون"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/عزير
  { category: "قصص الأنبياء", q: "من هو الرجل الذي صنع العجل من الذهب لقوم موسى ليعبدوه في غيابه؟", a: "السامري", choices: ["قارون", "هامان", "السامري", "بلعام"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/السامري
  { category: "قصص الأنبياء", q: "إلى أين هاجر إبراهيم عليه السلام مع زوجته سارة وابن أخيه لوط بعد خروجه من بابل؟", a: "الشام (فلسطين)", choices: ["مصر", "مكة المكرمة", "الشام (فلسطين)", "اليمن"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/إبراهيم
  { category: "قصص الأنبياء", q: "من هو النبي الذي سُجن ظلماً لعدة سنوات وكان يؤول الرؤى في السجن؟", a: "يوسف عليه السلام", choices: ["أيوب عليه السلام", "يوسف عليه السلام", "دانيال", "موسى عليه السلام"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/يوسف
  { category: "قصص الأنبياء", q: "كم كان عمر النبي محمد ﷺ عندما توفيت أمه آمنة بنت وهب؟", a: "ست سنوات", choices: ["سنتان", "أربع سنوات", "ست سنوات", "ثماني سنوات"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/محمد
  { category: "قصص الأنبياء", q: "من هو جد النبي محمد ﷺ الذي تولى كفالته بعد وفاة أمه؟", a: "عبد المطلب", choices: ["أبو طالب", "عبد مناف", "عبد المطلب", "هاشم"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/محمد
  { category: "قصص الأنبياء", q: "ما اسم النبي الذي ذُكر مقروناً بإسماعيل وإدريس في سورة الأنبياء بوصف 'كل من الصابرين'؟", a: "ذو الكفل", choices: ["إلياس", "اليسع", "ذو الكفل", "شعيب"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/ذو_الكفل
  { category: "قصص الأنبياء", q: "ما هو النبي الذي قال عنه النبي ﷺ: 'رحم الله أخي... لو لبثت في السجن ما لبث لأجبت الداعي'؟", a: "يوسف عليه السلام", choices: ["يونس عليه السلام", "يوسف عليه السلام", "موسى عليه السلام", "يحيى عليه السلام"], difficulty: "hard", points: 200, power: false }, // Source: https://sunnah.com/bukhari:3372
  { category: "قصص الأنبياء", q: "في أي سورة وردت تفاصيل قصة أصحاب الأخدود والملك الظالم؟", a: "سورة البروج", choices: ["سورة الكهف", "سورة البروج", "سورة الفجر", "سورة الفيل"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/أصحاب_الأخدود
  { category: "قصص الأنبياء", q: "من الذي كفل مريم العذراء وتولى رعايتها في المحراب كما ورد في القرآن؟", a: "زكريا عليه السلام", choices: ["يحيى عليه السلام", "عمران", "زكريا عليه السلام", "عيسى عليه السلام"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/زكريا
  { category: "قصص الأنبياء", q: "ما اسم الصنم الذي كان يعبده قوم إلياس عليه السلام في مدينة بعلبك؟", a: "بعل", choices: ["ود", "بعل", "يغوث", "يعوق"], difficulty: "hard", points: 200, power: false }, // Source: https://ar.wikipedia.org/wiki/إلياس
  { category: "قصص الأنبياء", q: "من هو النبي الذي قبض الله روحه في السماء الرابعة؟", a: "إدريس عليه السلام", choices: ["عيسى عليه السلام", "إلياس عليه السلام", "إدريس عليه السلام", "يحيى عليه السلام"], difficulty: "hard", points: 200, power: false } // Source: https://ar.wikipedia.org/wiki/إدريس
];