export const proverbsQuestions = [
  { category: "أمثال شعبية", q: "أكمل المثل: 'الغايب...'", a: "عذره معاه", choices: ["مالهوش مكان", "عذره معاه", "ينسى", "يفوت نص عمره"], difficulty: "super easy", points: 50, power: false }, // Proof: Common Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'الجار قبل...'", a: "الدار", choices: ["الأهل", "المال", "الدار", "الصحبة"], difficulty: "super easy", points: 50, power: false }, // Proof: Common Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'الغريق يتعلق بـ...'", a: "قشة", choices: ["خشبة", "حبل", "صخرة", "قشة"], difficulty: "super easy", points: 50, power: false }, // Proof: Common Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'الصبر مفتاح...'", a: "الفرج", choices: ["السعادة", "النجاح", "الفرج", "الجنان"], difficulty: "super easy", points: 50, power: false }, // Proof: Common Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'السكوت علامة...'", a: "الرضا", choices: ["الخوف", "الرضا", "الضعف", "الجهل"], difficulty: "super easy", points: 50, power: false }, // Proof: Common Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'حبل الكذب...'", a: "قصير", choices: ["مقطوع", "قصير", "طويل", "ضعيف"], difficulty: "super easy", points: 50, power: false }, // Proof: Common Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'العلم في الصغر كالنقش على...'", a: "الحجر", choices: ["الماء", "الورق", "الحجر", "الرمل"], difficulty: "super easy", points: 50, power: false }, // Proof: Common Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'عذر أقبح من...'", a: "ذنب", choices: ["فعل", "ذنب", "خطأ", "كذبة"], difficulty: "super easy", points: 50, power: false }, // Proof: Common Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'درهم وقاية خير من قنطار...'", a: "علاج", choices: ["ذهب", "فضة", "علاج", "دواء"], difficulty: "super easy", points: 50, power: false }, // Proof: Common Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'من جَدّ وجد، ومن زرع...'", a: "حصد", choices: ["قطف", "أكل", "حصد", "باع"], difficulty: "super easy", points: 50, power: false }, // Proof: Common Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'لسانك حصانك، إن صنته صانك وإن...'", a: "خنته هانك", choices: ["تركته فاتك", "خنته هانك", "أهملته هانك", "بعته أهانك"], difficulty: "easy", points: 100, power: false }, // Proof: Common Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'من شابه أباه فما...'", a: "ظلم", choices: ["أخطأ", "كذب", "ظلم", "خسر"], difficulty: "easy", points: 100, power: false }, // Proof: Common Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'الطيور على أشكالها...'", a: "تقع", choices: ["تطير", "تقع", "تغرد", "تهاجر"], difficulty: "easy", points: 100, power: false }, // Proof: Common Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'يا غريب كن...'", a: "أديب", choices: ["أديب", "حذر", "ذكي", "صامت"], difficulty: "easy", points: 100, power: false }, // Proof: Common Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'عصفور في اليد خير من عشرة على...'", a: "الشجرة", choices: ["السقف", "الأرض", "الشجرة", "الغصن"], difficulty: "easy", points: 100, power: false }, // Proof: Common Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'فاقد الشيء لا...'", a: "يعطيه", choices: ["يأخذه", "يعطيه", "يفهمه", "يملكه"], difficulty: "easy", points: 100, power: false }, // Proof: Common Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'يد واحدة لا...'", a: "تصفق", choices: ["تكتب", "تصفق", "تبني", "تزرع"], difficulty: "easy", points: 100, power: false }, // Proof: Common Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'ابن الوز...'", a: "عوام", choices: ["طائر", "عوام", "ذكي", "صياد"], difficulty: "easy", points: 100, power: false }, // Proof: Common Egyptian proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'القرد في عين أمه...'", a: "غزال", choices: ["أسد", "أمير", "غزال", "بطل"], difficulty: "easy", points: 100, power: false }, // Proof: Common Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'الباب اللي يجيك منه الريح...'", a: "سده واستريح", choices: ["سده واستريح", "خليه مفتوح", "اقفله واحبسه", "اتركه يهوي"], difficulty: "easy", points: 100, power: false }, // Proof: Common Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'الضرب في الميت...'", a: "حرام", choices: ["عيب", "حرام", "خسارة", "صعب"], difficulty: "easy", points: 100, power: false }, // Proof: Common Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'البحر يحب...'", a: "الزيادة", choices: ["السمك", "الزيادة", "الملح", "الهدوء"], difficulty: "easy", points: 100, power: false }, // Proof: Common Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'الخبر النهاردة بفلوس، بكرة يبقى...'", a: "بلاش", choices: ["رخيص", "بلاش", "غالي", "معروف"], difficulty: "easy", points: 100, power: false }, // Proof: Common Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'اللي بيته من قزاز...'", a: "ما يرمي الناس بالطوب", choices: ["يخاف من الريح", "ينظفه زين", "ما يرمي الناس بالطوب", "يسكر الستارة"], difficulty: "easy", points: 100, power: false }, // Proof: Common Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'تجري الرياح بما لا...'", a: "تشتهي السفن", choices: ["يريد البحارة", "تتوقع الجبال", "تتحمل البيوت", "تشتهي السفن"], difficulty: "easy", points: 100, power: false }, // Proof: Poetry by Al-Mutanabbi used as proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'ما طار طير وارتفع إلا كما طار...'", a: "وقع", choices: ["وقع", "رجع", "اختفى", "نزل"], difficulty: "easy", points: 100, power: false }, // Proof: Common Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'من حفر حفرة لأخيه...'", a: "وقع فيها", choices: ["دفنه فيها", "وقع فيها", "ساعده فيها", "هرب منها"], difficulty: "easy", points: 100, power: false }, // Proof: Common Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'اتقِ شر الحليم إذا...'", a: "غضب", choices: ["تكلم", "غضب", "سكت", "ضحك"], difficulty: "easy", points: 100, power: false }, // Proof: Common Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل السوري/الشامي: 'إذا كان حبيبك عسل...'", a: "لا تلحسه كله", choices: ["خبي منه لبكرة", "لا تلحسه كله", "حطه بعيونك", "طعمه للناس"], difficulty: "medium", points: 150, power: false }, // Proof: Common Levantine proverb
  { category: "أمثال شعبية", q: "أكمل المثل الخليجي: 'اللي ما يعرف الصقر...'", a: "يشويه", choices: ["يخليه يطير", "يربيه", "يشويه", "يخاف منه"], difficulty: "medium", points: 150, power: false }, // Proof: Common Gulf proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'اللي إيده في المية مش زي اللي إيده في...'", a: "النار", choices: ["الثلج", "الهوا", "النار", "الطين"], difficulty: "easy", points: 100, power: false }, // Proof: Common Egyptian proverb
  { category: "أمثال شعبية", q: "ما هو المثل الذي يضرب لمن يتدخل في شؤون الآخرين؟", a: "من تدخل فيما لا يعنيه لقى ما لا يرضيه", choices: ["الباب اللي يجيك منه الريح سده", "من تدخل فيما لا يعنيه لقى ما لا يرضيه", "اللي استحوا ماتوا", "يا غريب كن أديب"], difficulty: "easy", points: 100, power: false }, // Proof: Common Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'ضربني وبكى...'", a: "سبقني واشتكى", choices: ["راح زعلان", "سبقني واشتكى", "قال أنا المظلوم", "طلع يضحك"], difficulty: "easy", points: 100, power: false }, // Proof: Common Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل الشامي: 'يا جبل ما يهزك...'", a: "ريح", choices: ["زلزال", "بركان", "مطر", "ريح"], difficulty: "easy", points: 100, power: false }, // Proof: Common Levantine proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'الوقت كالسيف إن لم تقطعه...'", a: "قطعك", choices: ["أدمدمك", "قطعك", "سبقك", "قتلك"], difficulty: "easy", points: 100, power: false }, // Proof: Common Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'الحسود لا...'", a: "يسود", choices: ["يسود", "يعيش", "ينام", "يفرح"], difficulty: "medium", points: 150, power: false }, // Proof: Common Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'لو كان فيه خير ما رماه...'", a: "الطير", choices: ["البحر", "الناس", "الطير", "الكلب"], difficulty: "medium", points: 150, power: false }, // Proof: Common Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'نوم الظالم...'", a: "عبادة", choices: ["راحة", "عبادة", "ستر", "خوف"], difficulty: "medium", points: 150, power: false }, // Proof: Common Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل الدارج: 'يا واخد القرد على ماله...'", a: "يروح المال ويبقى القرد", choices: ["تخسر مالك", "يروح المال ويبقى القرد", "القرد يبقى قرد", "تسعد بماله"], difficulty: "medium", points: 150, power: false }, // Proof: Common Egyptian proverb
  { category: "أمثال شعبية", q: "أكمل المثل الشعبي: 'القرعة تتباهى بـ...'", a: "شعر بنت أختها", choices: ["شعرها الطويل", "مال زوجها", "جمال وجهها", "شعر بنت أختها"], difficulty: "medium", points: 150, power: false }, // Proof: Common Egyptian proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'يا مأمنة للرجال يا مأمنة لـ...'", a: "المية في الغربال", choices: ["السمك في البحر", "المية في الغربال", "الريح في الشباك", "النار في الثلج"], difficulty: "medium", points: 150, power: false }, // Proof: Common Egyptian proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'اللي اختشوا...'", a: "ماتوا", choices: ["عاشوا", "ماتوا", "ناموا", "سكتوا"], difficulty: "medium", points: 150, power: false }, // Proof: Common Egyptian proverb
  { category: "أمثال شعبية", q: "أكمل المثل المغربي: 'اللي بغا العسل يصبر لـ...'", a: "قريص النحل", choices: ["غلاء السعر", "قريص النحل", "طول الطريق", "مرارة الصبر"], difficulty: "medium", points: 150, power: false }, // Proof: Common Maghrebi proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'إن كبر ابنك...'", a: "خاويه", choices: ["زوجه", "علمه", "خاويه", "سفره"], difficulty: "medium", points: 150, power: false }, // Proof: Common Levantine/Egyptian proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'النار ما تحرق إلا...'", a: "رجل واطيها", choices: ["رجل واطيها", "اللي جنبها", "الحطب", "نفسها"], difficulty: "medium", points: 150, power: false }, // Proof: Common Levantine/Gulf proverb
  { category: "أمثال شعبية", q: "أكمل المثل المصري: 'اللي ما يعرفش يقول...'", a: "عدس", choices: ["معرفش", "عدس", "فول", "خلاص"], difficulty: "medium", points: 150, power: false }, // Proof: Common Egyptian proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'جاء يكحلها...'", a: "عماها", choices: ["زينها", "خربها", "عماها", "طينها"], difficulty: "medium", points: 150, power: false }, // Proof: Common Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'المتعوس متعوس ولو علقوا على باب بيته...'", a: "فانوس", choices: ["ألماس", "فانوس", "ذهب", "فلوس"], difficulty: "medium", points: 150, power: false }, // Proof: Common Levantine/Egyptian proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'اقلب القدرة على فمها تطلع البنت...'", a: "لأمها", choices: ["لأبوها", "لخالتها", "لأمها", "لجدتها"], difficulty: "medium", points: 150, power: false }, // Proof: Common Egyptian proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'قالوا للحرامي احلف قال...'", a: "جاني الفرج", choices: ["والله ما أسرق", "جاني الفرج", "توبت لله", "ما شفت شي"], difficulty: "medium", points: 150, power: false }, // Proof: Common Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'اللي ما يطول العنب حامضٍ عنه...'", a: "يقول", choices: ["يرميه", "يقول", "يخليه", "يقطفه"], difficulty: "medium", points: 150, power: false }, // Proof: Common Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'أسمع كلامك أصدقك أشوف أمورك...'", a: "أستعجب", choices: ["أكذبك", "أستغرب", "أستعجب", "أضحك"], difficulty: "medium", points: 150, power: false }, // Proof: Common Egyptian proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'رُبّ ضارة...'", a: "نافعة", choices: ["مؤذية", "نافعة", "مفيدة", "جارحة"], difficulty: "easy", points: 100, power: false }, // Proof: Common Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'كل فتاة بأبيها...'", a: "معجبة", choices: ["مغرمة", "معجبة", "شبيهة", "متعلقة"], difficulty: "medium", points: 150, power: false }, // Proof: Common Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'الطول طول نخلة والعقل عقل...'", a: "سخلة", choices: ["نملة", "طفل", "بصلة", "سخلة"], difficulty: "medium", points: 150, power: false }, // Proof: Common Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'ذيل الكلب عمره ما...'", a: "ينعدل", choices: ["يطول", "ينعدل", "ينقص", "ينتصب"], difficulty: "medium", points: 150, power: false }, // Proof: Common Egyptian proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'ما حك جلدك مثل...'", a: "ظفرك", choices: ["يدك", "ظفرك", "صديقك", "طبيبك"], difficulty: "medium", points: 150, power: false }, // Proof: Common Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'مصائب قوم عند قوم...'", a: "فوائد", choices: ["أحزان", "مكاسب", "أفراح", "فوائد"], difficulty: "medium", points: 150, power: false }, // Proof: Poetry by Al-Mutanabbi used as proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'لا يلدغ المؤمن من جحر...'", a: "مرتين", choices: ["أبداً", "مرتين", "ثلاثاً", "قط"], difficulty: "medium", points: 150, power: false }, // Proof: Prophetic Hadith used as proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'من أمن العقوبة أساء...'", a: "الأدب", choices: ["العمل", "الأدب", "التصرف", "الظن"], difficulty: "medium", points: 150, power: false }, // Proof: Common Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'القرش الأبيض ينفع في اليوم...'", a: "الأسود", choices: ["الصعب", "الأسود", "الطويل", "الماضي"], difficulty: "medium", points: 150, power: false }, // Proof: Common Egyptian proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'أعطِ الخبز لخبازه ولو أكل...'", a: "نصفه", choices: ["كله", "نصفه", "ربعه", "ثلاثة أرباعه"], difficulty: "medium", points: 150, power: false }, // Proof: Common Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'يخلق من الشبه...'", a: "أربعين", choices: ["أربعين", "عشرين", "عشرة", "مئة"], difficulty: "medium", points: 150, power: false }, // Proof: Common Arabic proverb
  { category: "أمثال شعبية", q: "ما معنى المثل الشهير 'رجع بخفي حنين'؟", a: "عاد خائباً", choices: ["عاد غنياً", "عاد منتصراً", "عاد خائباً", "عاد مسرعاً"], difficulty: "hard", points: 200, power: false }, // Proof: Historical Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'كأن على رؤوسهم...'", a: "الطير", choices: ["الماء", "النار", "الطير", "التراب"], difficulty: "hard", points: 200, power: false }, // Proof: Historical Arabic proverb
  { category: "أمثال شعبية", q: "ما معنى المثل العربي 'يداك أوكتا وفوك نفخ'؟", a: "أنت من جلب المشكلة لنفسك", choices: ["الرياح قوية جداً", "الكلام أكثر من الأفعال", "أنت من جلب المشكلة لنفسك", "التعاون يحل المصاعب"], difficulty: "hard", points: 200, power: false }, // Proof: Historical Arabic proverb from Majma' al-Amthal
  { category: "أمثال شعبية", q: "ما معنى المثل: 'سبق السيف العذل'؟", a: "فات وقت اللوم", choices: ["اشتد القتال", "فات وقت اللوم", "السيف أثقل من الكلام", "الحق مع الأقوى"], difficulty: "hard", points: 200, power: false }, // Proof: Historical Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل العربي القديم: 'على نفسها جنت...'", a: "براقش", choices: ["هند", "ليلى", "براقش", "سعاد"], difficulty: "hard", points: 200, power: false }, // Proof: Historical Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل العراقي: 'عصفور كفل زرزور واثنينهم...'", a: "طيارة", choices: ["بالقفص", "طيارة", "على الشجرة", "ذابحهم الجوع"], difficulty: "hard", points: 200, power: false }, // Proof: Common Iraqi proverb
  { category: "أمثال شعبية", q: "ماذا يعني المثل 'وافق شن طبقة'؟", a: "تطابق شخصين في الصفات", choices: ["اختلاف الآراء", "تطابق شخصين في الصفات", "انتهاء المشكلة", "بداية حرب"], difficulty: "hard", points: 200, power: false }, // Proof: Historical Arabic proverb
  { category: "أمثال شعبية", q: "ما هو أصل المثل 'مواعيد عرقوب'؟", a: "رجل اشتهر بإخلاف الوعود", choices: ["تاجر يفي بوعوده دائماً", "رجل اشتهر بإخلاف الوعود", "ملك حكيم", "فارس شجاع"], difficulty: "hard", points: 200, power: false }, // Proof: Historical Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل العربي الفصيح: 'قطعت جهيزة قول كل...'", a: "خطيب", choices: ["كاذب", "جاهل", "عالم", "خطيب"], difficulty: "hard", points: 200, power: false }, // Proof: Historical Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل: 'الصيف ضيعتِ...'", a: "اللبن", choices: ["الزرع", "اللبن", "الماء", "الحصاد"], difficulty: "hard", points: 200, power: false }, // Proof: Historical Arabic proverb
  { category: "أمثال شعبية", q: "ماذا يقصد بالمثل 'جزاؤه جزاء سنمار'؟", a: "نكران الجميل", choices: ["نكران الجميل", "المكافأة العظيمة", "العدل المطلق", "الخيانة العظمى"], difficulty: "hard", points: 200, power: false }, // Proof: Historical Arabic proverb
  { category: "أمثال شعبية", q: "المثل 'عادت حليمة إلى عادتها القديمة'.. من هي حليمة أصلاً؟", a: "زوجة حاتم الطائي", choices: ["أخت المتنبي", "زوجة حاتم الطائي", "ملكة سبأ", "أم عنترة بن شداد"], difficulty: "hard", points: 200, power: false }, // Proof: Historical Arabic folklore
  { category: "أمثال شعبية", q: "من هي القائلة للمثل الشهير: 'بيدي لا بيدي عمرو'؟", a: "الزباء (زنوبيا)", choices: ["شجر الدر", "الخنساء", "الزباء (زنوبيا)", "بلقيس"], difficulty: "hard", points: 200, power: false }, // Proof: Historical Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل العراقي الدارج: 'اللي ما يعرف يرقص يقول الأرض...'", a: "عوجة", choices: ["صلبة", "زلقة", "عوجة", "صغيرة"], difficulty: "medium", points: 150, power: false }, // Proof: Common Iraqi/Gulf proverb
  { category: "أمثال شعبية", q: "متى يضرب المثل: 'رمتني بدائها وانسلت'؟", a: "لمن يعيب غيره بما فيه", choices: ["لمن يهرب من المعركة", "لمن يعيب غيره بما فيه", "لمن ينكر الجميل", "لمن يسرق ويختفي"], difficulty: "hard", points: 200, power: false }, // Proof: Historical Arabic proverb
  { category: "أمثال شعبية", q: "أين يُضرب المثل العربي 'أبصر من زرقاء اليمامة'؟", a: "في قوة البصر", choices: ["في قوة البصر", "في شدة الذكاء", "في جمال العينين", "في سرعة البديهة"], difficulty: "hard", points: 200, power: false }, // Proof: Historical Arabic proverb
  { category: "أمثال شعبية", q: "أكمل المثل الفصيح: 'تمخض الجبل فولد...'", a: "فأراً", choices: ["أسداً", "فأراً", "بركاناً", "صخرة"], difficulty: "hard", points: 200, power: false } // Proof: Historical translated fable proverb
];