export const riddlesQuestions = [
  { category: "فوازير وألغاز", q: "ما هو الشيء الذي يكبر ويزداد كلما أخذت منه؟", a: "الحفرة", choices: ["الجبل", "البحر", "الحفرة", "الشجرة"], difficulty: "supereasy", points: 50, power: false }, // Proof: Riddle axiom - Digging dirt out makes a hole larger.
  { category: "فوازير وألغاز", q: "ما هو الشيء الذي يبكي بلا عيون ويمشي بلا أرجل؟", a: "السحابة", choices: ["الرياح", "السحابة", "الظل", "النهر"], difficulty: "supereasy", points: 50, power: false }, // Proof: Riddle axiom - Clouds move (walk) and drop rain (cry).
  { category: "فوازير وألغاز", q: "ما هو الشيء الذي له أسنان كثيرة ولكنه لا يعض أبداً؟", a: "المشط", choices: ["المنشار", "السحاب", "المشط", "الكتاب"], difficulty: "supereasy", points: 50, power: false }, // Proof: Riddle axiom - Combs have teeth for hair, not for biting.
  { category: "فوازير وألغاز", q: "أخت خالك، وليست خالتك.. فمن تكون؟", a: "الأم", choices: ["الجدة", "العمة", "الأم", "الابنة"], difficulty: "supereasy", points: 50, power: false }, // Proof: Logical deduction - Your uncle's sister who isn't your aunt must be your mother.
  { category: "فوازير وألغاز", q: "ما هو الشيء الذي يكتب كثيراً ولكنه لا يقرأ حرفاً؟", a: "القلم", choices: ["الكتاب", "الدفتر", "المحبرة", "القلم"], difficulty: "supereasy", points: 50, power: false }, // Proof: Riddle axiom - A pen writes text but lacks the ability to read.
  { category: "فوازير وألغاز", q: "نصنعه ونجلس حوله ونأكل منه، ولكنه لا يؤكل.. فما هو؟", a: "الطاولة", choices: ["الطعام", "الصحن", "الملح", "الطاولة"], difficulty: "supereasy", points: 50, power: false }, // Proof: Riddle axiom - We sit around a dining table to eat, but don't eat the table itself.
  { category: "فوازير وألغاز", q: "ما هو الشيء الذي تذبحه وتبكي عليه فوراً؟", a: "البصل", choices: ["الخروف", "الدجاج", "البصل", "الثوم"], difficulty: "supereasy", points: 50, power: false }, // Proof: Riddle axiom - Cutting (slaughtering) an onion releases gases that cause tears.
  { category: "فوازير وألغاز", q: "ما هو الشيء الذي ينبض بالحياة دائماً ولكنه بلا قلب؟", a: "الساعة", choices: ["الإنسان", "الساعة", "النبتة", "البحر"], difficulty: "supereasy", points: 50, power: false }, // Proof: Riddle axiom - Clocks tick (beat) constantly but have no biological heart.
  { category: "فوازير وألغاز", q: "ما هو الشيء المحيط بك من كل مكان ولا يمكنك إمساكه بيدك؟", a: "الهواء", choices: ["الماء", "الظل", "الهواء", "الصوت"], difficulty: "supereasy", points: 50, power: false }, // Proof: Riddle axiom - Air surrounds us physically but cannot be grabbed.
  { category: "فوازير وألغاز", q: "ما هو الشيء الذي يرتفع دائماً ولا ينزل أبداً بمرور السنين؟", a: "العمر", choices: ["الوزن", "الطول", "العمر", "الحرارة"], difficulty: "supereasy", points: 50, power: false }, // Proof: Logical axiom - Biological age only increases over time.
  { category: "فوازير وألغاز", q: "ما هو الشيء الذي تراه في النهار مرة وفي الليل ثلاث مرات؟", a: "حرف اللام", choices: ["القمر", "النجوم", "حرف اللام", "الشمس"], difficulty: "easy", points: 100, power: false }, // Proof: Wordplay - The Arabic word 'النهار' has one 'ل', and 'الليل' has three 'ل'.
  { category: "فوازير وألغاز", q: "شيء إذا وضعناه في الثلاجة لا يبرد أبداً؟", a: "الفلفل الحار", choices: ["الماء", "اللحم", "الفلفل الحار", "البيض"], difficulty: "easy", points: 100, power: false }, // Proof: Linguistic pun - 'Hot' pepper remains 'hot' (spicy) even when cold.
  { category: "فوازير وألغاز", q: "من هو الشخص الذي يرى عدوه وصديقه بعين واحدة؟", a: "الأعور", choices: ["الكاذب", "الأعور", "الظالم", "الرسام"], difficulty: "easy", points: 100, power: false }, // Proof: Literal definition - A one-eyed person views everything with their single eye.
  { category: "فوازير وألغاز", q: "ما هو الشيء الذي يتكلم بكل لغات العالم بطلاقة دون أن يتعلمها؟", a: "صدى الصوت", choices: ["المذياع", "الهاتف", "المترجم", "صدى الصوت"], difficulty: "easy", points: 100, power: false }, // Proof: Riddle axiom - Echoes reflect any spoken language identically.
  { category: "فوازير وألغاز", q: "ما هو الشيء الذي له أربع أرجل ولكنه لا يمشي أبداً؟", a: "الكرسي", choices: ["الدولاب", "الكرسي", "الكلب", "الطفل"], difficulty: "easy", points: 100, power: false }, // Proof: Riddle axiom - Chairs have physical legs for support, not for movement.
  { category: "فوازير وألغاز", q: "ما هو الشيء الذي يملك ثقوباً كثيرة ولكنه يحفظ الماء داخله؟", a: "الإسفنج", choices: ["المصفاة", "الغربال", "الإسفنج", "الكيس"], difficulty: "easy", points: 100, power: false }, // Proof: Riddle axiom - Sponges are porous but highly absorbent materials.
  { category: "فوازير وألغاز", q: "ابن أمك وأبوك وليس بأختك ولا بأخيك، فمن هو؟", a: "أنت", choices: ["خالك", "ابن عمك", "أنت", "جارك"], difficulty: "easy", points: 100, power: false }, // Proof: Logical deduction - The only other child of your parents who isn't a sibling is yourself.
  { category: "فوازير وألغاز", q: "دولة عربية من 3 حروف، إذا حذفنا آخر حرف أصبحت اسم حيوان أليف؟", a: "قطر", choices: ["مصر", "قطر", "يمن", "عُمان"], difficulty: "easy", points: 100, power: false }, // Proof: Wordplay - Removing the last letter of 'قطر' (Qatar) leaves 'قط' (Cat).
  { category: "فوازير وألغاز", q: "ما هو الشيء الذي كلما كثر حراسه زاد احتمال ضياعه؟", a: "السر", choices: ["المال", "الذهب", "السر", "الوقت"], difficulty: "easy", points: 100, power: false }, // Proof: Riddle axiom - Secrets are exposed when known by too many people.
  { category: "فوازير وألغاز", q: "ما هو الشيء الذي يموت فوراً إذا شرب الماء؟", a: "النار", choices: ["النار", "الثلج", "الملح", "السكر"], difficulty: "easy", points: 100, power: false }, // Proof: Riddle axiom - Water extinguishes fire.
  { category: "فوازير وألغاز", q: "ما هو الشيء الذي له رأس واحد ولكن بلا عقل أو تفكير؟", a: "الدبوس", choices: ["الدبوس", "القلم", "الوتد", "المسمار"], difficulty: "easy", points: 100, power: false }, // Proof: Riddle axiom - Pins have a flat top called a 'head' but are inanimate.
  { category: "فوازير وألغاز", q: "ما هو الشيء الذي يخرج من الماء، ولكنه يموت إذا عاد إليه؟", a: "الملح", choices: ["السمك", "الملح", "الإسفنج", "اللؤلؤ"], difficulty: "easy", points: 100, power: false }, // Proof: Riddle axiom - Salt is extracted from seawater but dissolves back into it.
  { category: "فوازير وألغاز", q: "ما هو الشيء الذي له قشرة من الخارج ولب من الداخل ويؤكل مسلوقاً أو مقلياً؟", a: "البيضة", choices: ["البيضة", "الجوز", "البرتقال", "التفاحة"], difficulty: "easy", points: 100, power: false }, // Proof: Riddle axiom - Eggs fit this exact culinary description.
  { category: "فوازير وألغاز", q: "ما هو الشيء الذي يذوب في الماء ولا يختفي طعمه أبداً؟", a: "السكر", choices: ["السكر", "الرمل", "الثلج", "الجليد"], difficulty: "easy", points: 100, power: false }, // Proof: Riddle axiom - Sugar dissolves into an invisible solution but retains its sweetness.
  { category: "فوازير وألغاز", q: "ما هو الشيء الذي يزداد بللاً كلما استخدمته في التجفيف أكثر؟", a: "المنشفة", choices: ["الإسفنجة", "الشمس", "المنشفة", "الرياح"], difficulty: "easy", points: 100, power: false }, // Proof: Riddle axiom - Towels absorb moisture from other objects, becoming wet themselves.
  { category: "فوازير وألغاز", q: "شيء تملكه أنت، ولكن جميع من حولك يستخدمونه أكثر منك.. فما هو؟", a: "اسمك", choices: ["مالك", "هاتفك", "اسمك", "سيارتك"], difficulty: "easy", points: 100, power: false }, // Proof: Riddle axiom - A person's name is primarily used by others to address them.
  { category: "فوازير وألغاز", q: "ما هو الشيء الذي يحتوي على مدن بلا منازل، وأنهار بلا ماء؟", a: "الخريطة", choices: ["الكرة الأرضية", "القاموس", "اللوحة", "الخريطة"], difficulty: "easy", points: 100, power: false }, // Proof: Riddle axiom - Maps represent geography visually without physical attributes.
  { category: "فوازير وألغاز", q: "إذا سقطت انكسرت، وإذا ابتسمت لها ابتسمت لك، فما هي؟", a: "المرآة", choices: ["الزجاجة", "الكاميرا", "المرآة", "اللوحة"], difficulty: "medium", points: 150, power: false }, // Proof: Riddle axiom - Mirrors reflect expressions perfectly and are made of fragile glass.
  { category: "فوازير وألغاز", q: "كلما كثر وجوده من حولك، قلّت قدرتك على الرؤية بوضوح، فما هو؟", a: "الضباب", choices: ["الضباب", "الهواء", "النور", "الدخان"], difficulty: "medium", points: 150, power: false }, // Proof: Riddle axiom - Fog reduces visibility as its density increases.
  { category: "فوازير وألغاز", q: "شيء يمتلك عيناً واحدة ولكنه لا يستطيع الرؤية بها أبداً؟", a: "إبرة الخياطة", choices: ["الكاميرا", "إبرة الخياطة", "التلسكوب", "العاصفة"], difficulty: "medium", points: 150, power: false }, // Proof: Riddle axiom - The hole in a needle is called an 'eye' but serves no visual function.
  { category: "فوازير وألغاز", q: "ما هو الباب الذي لا يمكنك فتحه حتى لو استخدمت كل مفاتيح العالم؟", a: "الباب المفتوح", choices: ["باب السجن", "الباب المفتوح", "باب السيارة", "باب الخزنة"], difficulty: "medium", points: 150, power: false }, // Proof: Logical paradox - A door that is already open cannot be opened further.
  { category: "فوازير وألغاز", q: "ما هو المبنى المليء بالقصص والروايات من الأرض إلى السقف؟", a: "المكتبة", choices: ["المتحف", "المكتبة", "المدرسة", "المسرح"], difficulty: "medium", points: 150, power: false }, // Proof: Riddle axiom - Libraries physically house thousands of storybooks.
  { category: "فوازير وألغاز", q: "لدي إبهام وأربعة أصابع، لكنني لست من اللحم والعظام.. فما أنا؟", a: "القفاز", choices: ["القفاز", "المشط", "الشوكة", "المروحة"], difficulty: "medium", points: 150, power: false }, // Proof: Riddle axiom - Gloves are shaped exactly like hands but made of fabric.
  { category: "فوازير وألغاز", q: "عقرب لا يلدغ ولا يخيف أحداً مهما اقترب منك، فما هو؟", a: "عقرب الساعة", choices: ["عقرب الصحراء", "عقرب الساعة", "عقرب سام", "برج العقرب"], difficulty: "medium", points: 150, power: false }, // Proof: Linguistic pun - Clock hands are called 'عقارب' (scorpions) in Arabic.
  { category: "فوازير وألغاز", q: "ما هو الشيء الذي يقرصك بشدة في الشتاء ولا تراه أبداً؟", a: "البرد", choices: ["الذباب", "الجوع", "البرد", "الخوف"], difficulty: "medium", points: 150, power: false }, // Proof: Riddle axiom - Severe cold causes a physical stinging sensation like a pinch.
  { category: "فوازير وألغاز", q: "ما هو الشيء الذي له رقبة طويلة ولكنه بلا رأس؟", a: "الزجاجة", choices: ["القميص", "الزجاجة", "الشمعة", "الثعبان"], difficulty: "medium", points: 150, power: false }, // Proof: Riddle axiom - The top part of a bottle is called its neck.
  { category: "فوازير وألغاز", q: "أحتوي على آلاف الكلمات، ولكنني لا أنطق بحرف واحد، فما أنا؟", a: "الكتاب", choices: ["الصورة", "التلفاز", "الكتاب", "اللوحة"], difficulty: "medium", points: 150, power: false }, // Proof: Riddle axiom - Books are full of text but are entirely silent.
  { category: "فوازير وألغاز", q: "ما هو الشيء الذي يقرصك في بطنك ولا تراه؟", a: "الجوع", choices: ["البرد", "الظلام", "الجوع", "الخوف"], difficulty: "medium", points: 150, power: false }, // Proof: Riddle axiom - Hunger causes stomach pangs often described as pinching.
  { category: "فوازير وألغاز", q: "ما هو الشيء الذي يدور حول البيت دون أن يتحرك من مكانه؟", a: "السور", choices: ["الطريق", "الهواء", "السور", "الظل"], difficulty: "medium", points: 150, power: false }, // Proof: Riddle axiom - Fences form a static perimeter around a property.
  { category: "فوازير وألغاز", q: "ما هو الشيء الذي له أوراق كثيرة ولكنه ليس شجرة؟", a: "الدفتر", choices: ["الدفتر", "المروحة", "الباب", "البيت"], difficulty: "medium", points: 150, power: false }, // Proof: Linguistic pun - Pages in a book/notebook are called 'أوراق' (leaves/papers) in Arabic.
  { category: "فوازير وألغاز", q: "ما هو الشيء الذي تراه بوضوح في الظلام ويختفي تماماً في النهار؟", a: "النجم", choices: ["الشمس", "النجم", "اللون الأحمر", "الطريق"], difficulty: "medium", points: 150, power: false }, // Proof: Riddle axiom - Stars are only visible against the dark night sky.
  { category: "فوازير وألغاز", q: "ما هو الشيء الذي لا يسير ولا ينجز عمله إلا بالضرب على رأسه؟", a: "المسمار", choices: ["الكرة", "المسمار", "الباب", "الحجر"], difficulty: "medium", points: 150, power: false }, // Proof: Riddle axiom - Nails must be struck with a hammer to function.
  { category: "فوازير وألغاز", q: "ما هو الشيء السائل الذي إذا غليته جمد وأصبح صلباً؟", a: "البيض", choices: ["الماء", "الزيت", "البيض", "الحليب"], difficulty: "medium", points: 150, power: false }, // Proof: Riddle axiom - Boiling an egg denatures its proteins, turning it solid.
  { category: "فوازير وألغاز", q: "ما هو الشيء الذي ينقلنا من مكان إلى آخر دون أن يتحرك خطوة واحدة؟", a: "الطريق", choices: ["السيارة", "القطار", "الطريق", "الحذاء"], difficulty: "medium", points: 150, power: false }, // Proof: Riddle axiom - Roads are static pathways that facilitate travel.
  { category: "فوازير وألغاز", q: "ما هو الشيء الذي يلبس قبعة وهو بلا رأس، وينمو في الغابات؟", a: "الفطر", choices: ["الفطر", "المسمار", "الجبل", "القلم"], difficulty: "medium", points: 150, power: false }, // Proof: Riddle axiom - Mushrooms have a cap (hat) but no biological head.
  { category: "فوازير وألغاز", q: "ما هو الشيء الذي له لسان طويل ولا يتكلم أو ينطق أبداً؟", a: "الحذاء", choices: ["الجرس", "الحذاء", "الطريق", "النهر"], difficulty: "medium", points: 150, power: false }, // Proof: Linguistic pun - The flap under the laces of a shoe is called a tongue.
  { category: "فوازير وألغاز", q: "ما هو الشيء الذي يولد كبيراً ثم يصغر بمرور الوقت حتى يختفي؟", a: "الشمعة", choices: ["الإنسان", "الشمعة", "الشجرة", "الجبل"], difficulty: "medium", points: 150, power: false }, // Proof: Riddle axiom - Candles melt and shrink as they burn.
  { category: "فوازير وألغاز", q: "بيت ليس فيه سكان ولا أبواب ولا نوافذ، فما هو؟", a: "بيت الشعر", choices: ["بيت النمل", "القبر", "بيت الشعر", "بيت العنكبوت"], difficulty: "medium", points: 150, power: false }, // Proof: Linguistic pun - A line of poetry is traditionally called a 'بيت' (house) in Arabic.
  { category: "فوازير وألغاز", q: "ما هو الشيء الذي يملك وجهاً واحداً ويدين ولا يملك أرجلاً؟", a: "الساعة", choices: ["المرآة", "الساعة", "العملة", "القميص"], difficulty: "medium", points: 150, power: false }, // Proof: Riddle axiom - Analog clocks have a face and hands but no legs.
  { category: "فوازير وألغاز", q: "ما هو الشيء الذي ترميه في الماء كلما احتجت إليه؟", a: "مرساة السفينة", choices: ["الكرة", "مرساة السفينة", "القمامة", "الشبكة"], difficulty: "medium", points: 150, power: false }, // Proof: Riddle axiom - Anchors are deployed (thrown) into water to secure a vessel.
  { category: "فوازير وألغاز", q: "ما هو الشيء الذي صانعه لا يحبه، ومشتريه لا يستخدمه، ومستخدمه لا يراه؟", a: "التابوت", choices: ["القفل", "التابوت", "المرآة", "السم"], difficulty: "hard", points: 200, power: false }, // Proof: Classic riddle logic - A coffin is bought for the deceased who cannot see it.
  { category: "فوازير وألغاز", q: "حامل ومحمول، نصفه ناشف ونصفه مبلول.. فما هو؟", a: "السفينة", choices: ["الطائر", "السفينة", "السمكة", "الغواص"], difficulty: "hard", points: 200, power: false }, // Proof: Riddle axiom - Ships carry cargo (محمول) and are carried by water (حامل), floating half-submerged.
  { category: "فوازير وألغاز", q: "مدينة حمراء، أسوارها خضراء، بذورها سوداء وسكانها عبيد.. ما هي؟", a: "البطيخة", choices: ["التفاحة", "البطيخة", "الرمانة", "الفراولة"], difficulty: "hard", points: 200, power: false }, // Proof: Classic Arabic riddle - Describes the colors and seeds of a watermelon.
  { category: "فوازير وألغاز", q: "طير طار في الأقطار، لا له ريش ولا منقار.. ما هو؟", a: "الدخان", choices: ["الغبار", "الدخان", "الصاروخ", "السهم"], difficulty: "hard", points: 200, power: false }, // Proof: Classic Arabic riddle - Smoke rises and travels like a bird but lacks biological features.
  { category: "فوازير وألغاز", q: "ما هو الشيء الذي يضحك بلا فم ويبكي بلا عيون في الطبيعة؟", a: "السحاب والبرق", choices: ["السحاب والبرق", "السماء والأرض", "الشمس والقمر", "البحر والرياح"], difficulty: "hard", points: 200, power: false }, // Proof: Riddle axiom - Lightning flashing is likened to laughter, and rain to tears.
  { category: "فوازير وألغاز", q: "ما هو الشيء الذي له وجهان متناقضان ولا جسد له؟", a: "العملة المعدنية", choices: ["العملة المعدنية", "المرآة", "الكتاب", "اللوحة"], difficulty: "hard", points: 200, power: false }, // Proof: Riddle axiom - Coins have two distinct sides (heads/tails) but no thick body.
  { category: "فوازير وألغاز", q: "شيء يمتلك مفاتيح كثيرة ولكنه لا يستطيع فتح أي باب، فما هو؟", a: "البيانو", choices: ["الكمبيوتر", "البيانو", "الخزنة", "القفل المكسور"], difficulty: "hard", points: 200, power: false }, // Proof: Linguistic pun - Piano keys are called 'مفاتيح' in Arabic.
  { category: "فوازير وألغاز", q: "شيء يمكنك التقاطه بسهولة ولكن لا يمكنك رميه أبداً؟", a: "الزكام", choices: ["الكرة", "السهم", "الزكام", "الظل"], difficulty: "hard", points: 200, power: false }, // Proof: Wordplay - You can 'catch' a cold (التقاط الزكام), but you cannot literally throw it away.
  { category: "فوازير وألغاز", q: "أخوان يلاحق أحدهما الآخر طوال اليوم بانتظام ولكن لا يلتقيان أبداً؟", a: "عجلات الدراجة", choices: ["الليل والنهار", "عقارب الساعة", "الشمس والقمر", "عجلات الدراجة"], difficulty: "hard", points: 200, power: false }, // Proof: Riddle axiom - The front and back wheels of a bicycle move together but never touch. (Note: Wait, clock hands DO meet. Bicycle wheels DO NOT. So I fixed the answer from عقارب الساعة to عجلات الدراجة).
  { category: "فوازير وألغاز", q: "أملك فروعاً كثيرة، ولكن ليس لدي جذع أو أوراق أو ثمار.. فما أنا؟", a: "البنك", choices: ["البنك", "الظل", "النهر", "الطريق"], difficulty: "hard", points: 200, power: false }, // Proof: Linguistic pun - Financial institutions have 'branches' (فروع) but aren't trees.
  { category: "فوازير وألغاز", q: "شيء كلما أخذت منه خطوة، تركته وراءك أكثر.. فما هو؟", a: "أثر القدم", choices: ["العمر", "أثر القدم", "التراب", "الذكريات"], difficulty: "hard", points: 200, power: false }, // Proof: Riddle axiom - Footprints are left behind as you walk forward.
  { category: "فوازير وألغاز", q: "ما هو الشيء الذي يمكنك كسره بسهولة حتى دون أن تلمسه أو تراه؟", a: "الوعد", choices: ["الزجاج", "الخشب", "القلب", "الوعد"], difficulty: "hard", points: 200, power: false }, // Proof: Riddle axiom - Promises are conceptual and can be 'broken' metaphorically.
  { category: "فوازير وألغاز", q: "ما هو الشيء الذي يصعد وينزل باستمرار، ولكنه لا يتحرك من مكانه؟", a: "الدرج (السلالم)", choices: ["المصعد", "الشمس", "الدرج (السلالم)", "العمر"], difficulty: "hard", points: 200, power: false }, // Proof: Riddle axiom - Stairs go up and down building levels but are stationary structures.
  { category: "فوازير وألغاز", q: "أظهر مرتين في الدقيقة، ومرة واحدة في القرن، ولا أظهر أبداً في الساعة.. فمن أنا؟", a: "حرف القاف", choices: ["الرقم واحد", "حرف القاف", "الثانية", "النقطة"], difficulty: "hard", points: 200, power: false }, // Proof: Wordplay - Letter counting: 'الدقيقة' (2 قاف), 'القرن' (1 قاف), 'الساعة' (0 قاف).
  { category: "فوازير وألغاز", q: "أقوم بالحلاقة عشرات المرات كل يوم، ومع ذلك تظل لحيتي كما هي.. فمن أنا؟", a: "الحلاق", choices: ["الممثل", "الحلاق", "الجراح", "النحات"], difficulty: "hard", points: 200, power: false } // Proof: Riddle axiom - A barber shaves others' beards, not his own.
];