export const scienceQuestions = [
  { category: "علماء واختراعات", q: "من هو مخترع المصباح الكهربائي التجاري الشائع؟", a: "توماس إديسون", choices: ["نيكولا تسلا", "ألبرت أينشتاين", "توماس إديسون", "إسحاق نيوتن"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/توماس_إديسون
  { category: "علماء واختراعات", q: "من هو العالم المسلم الذي يُعد مؤسس علم الجبر؟", a: "الخوارزمي", choices: ["ابن سينا", "جابر بن حيان", "ابن الهيثم", "الخوارزمي"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/محمد_بن_موسى_الخوارزمي
  { category: "علماء واختراعات", q: "من هو الطبيب العربي الذي اكتشف الدورة الدموية الصغرى؟", a: "ابن النفيس", choices: ["ويليام هارفي", "ابن سينا", "الرازي", "ابن النفيس"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/ابن_النفيس
  { category: "علماء واختراعات", q: "من هو العالم الذي اكتشف البنسلين؟", a: "ألكسندر فلمنج", choices: ["ماري كوري", "لويس باستير", "روبرت كوخ", "ألكسندر فلمنج"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/ألكسندر_فلمنج
  { category: "علماء واختراعات", q: "من هو العالم الذي وضع قانون الجاذبية العام؟", a: "إسحاق نيوتن", choices: ["إسحاق نيوتن", "ألبرت أينشتاين", "غاليليو", "يوهانس كبلر"], difficulty: "super easy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/إسحاق_نيوتن
  { category: "علماء واختراعات", q: "من هو العالم الذي طوّر النظرية النسبية؟", a: "ألبرت أينشتاين", choices: ["نيلز بور", "ألبرت أينشتاين", "تشارلز داروين", "لويس باستير"], difficulty: "super easy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/ألبرت_أينشتاين
  { category: "علماء واختراعات", q: "من هي العالمة الحائزة على نوبل المرتبطة باكتشاف الراديوم والبولونيوم؟", a: "ماري كوري", choices: ["روزاليند فرانكلين", "أدا لوفلايس", "ماري كوري", "إيمي نوثر"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/ماري_كوري
  { category: "علماء واختراعات", q: "من هو المخترع الذي ارتبط اسمه باختراع الهاتف في الرواية الشائعة؟", a: "ألكسندر غراهام بيل", choices: ["غولييلمو ماركوني", "ألكسندر غراهام بيل", "توماس إديسون", "نيكولا تسلا"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/ألكسندر_غراهام_بيل
  { category: "علماء واختراعات", q: "من هو الطبيب اليوناني الذي يُلقب بـ 'أبي الطب'؟", a: "أبقراط", choices: ["جالينوس", "أبقراط", "ابن النفيس", "لويس باستير"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/أبقراط
  { category: "علماء واختراعات", q: "ما هو الجهاز الذي اخترعه يوهان غوتنبرغ وغيّر عالم النشر؟", a: "آلة الطباعة", choices: ["البوصلة", "آلة الطباعة", "التلسكوب", "المجهر"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/يوهانس_غوتنبرغ
  { category: "علماء واختراعات", q: "من هو العالم الذي أسس علم الوراثة من خلال تجاربه على نبات البازلاء؟", a: "غريغور مندل", choices: ["تشارلز داروين", "غريغور مندل", "لويس باستير", "روبرت هوك"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/غريغور_مندل
  { category: "علماء واختراعات", q: "من هو العالم العربي الذي يُلقب بـ 'أبي الكيمياء'؟", a: "جابر بن حيان", choices: ["ابن الهيثم", "أبو بكر الرازي", "جابر بن حيان", "ابن سينا"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/جابر_بن_حيان
  { category: "الفضاء والفلك", q: "ما هو أكبر كوكب في المجموعة الشمسية؟", a: "المشتري", choices: ["زحل", "الأرض", "المريخ", "المشتري"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/المشتري
  { category: "الفضاء والفلك", q: "أي كوكب في المجموعة الشمسية يُلقب بـ 'الكوكب الأحمر'؟", a: "المريخ", choices: ["الزهرة", "عطارد", "المشتري", "المريخ"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/المريخ
  { category: "الفضاء والفلك", q: "من هو أول إنسان صعد إلى الفضاء المداري؟", a: "يوري غاغارين", choices: ["نيل آرمسترونغ", "يوري غاغارين", "جون غلين", "باز ألدرين"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/يوري_غاغارين
  { category: "الفضاء والفلك", q: "ما هو النجم الذي يدور حوله كوكب الأرض؟", a: "الشمس", choices: ["القمر", "الشمس", "المشتري", "نجم الشمال"], difficulty: "super easy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/الشمس
  { category: "الفضاء والفلك", q: "ما هو اسم المجرة التي تضم نظامنا الشمسي؟", a: "درب التبانة", choices: ["المرأة المسلسلة", "درب التبانة", "سحابة ماجلان", "سومبريرو"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/درب_التبانة
  { category: "الفضاء والفلك", q: "ما هو الجرم السماوي الطبيعي الوحيد الذي يدور حول الأرض؟", a: "القمر", choices: ["المريخ", "القمر", "المذنب", "الزهرة"], difficulty: "super easy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/القمر
  { category: "الفضاء والفلك", q: "من هو رائد الفضاء الذي يُعد أول إنسان مشى على سطح القمر؟", a: "نيل آرمسترونغ", choices: ["يوري غاغارين", "نيل آرمسترونغ", "مايكل كولينز", "جون غلين"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/نيل_آرمسترونغ
  { category: "الفضاء والفلك", q: "ما هو الكوكب الأقرب إلى الشمس في نظامنا الشمسي؟", a: "عطارد", choices: ["الزهرة", "عطارد", "المريخ", "الأرض"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/عطارد
  { category: "الفضاء والفلك", q: "أي كواكب المجموعة الشمسية يشتهر بحلقاته الواضحة والكبيرة؟", a: "زحل", choices: ["المشتري", "نبتون", "زحل", "أورانوس"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/زحل
  { category: "الفضاء والفلك", q: "ما هي القوة الأساسية التي تُبقي الكواكب في مداراتها حول الشمس؟", a: "الجاذبية", choices: ["المغناطيسية", "الاحتكاك", "الجاذبية", "الضغط الجوي"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/جاذبية
  { category: "عالم الحيوان", q: "ما هو أسرع حيوان بري على وجه الأرض؟", a: "الفهد", choices: ["الأسد", "الحصان", "الغزال", "الفهد"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/فهد
  { category: "عالم الحيوان", q: "أي طائر لا يطير ويعيش بشكل رئيسي في نصف الكرة الجنوبي؟", a: "البطريق", choices: ["النعامة", "طائر الكيوي", "البطريق", "الطاووس"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/بطريق
  { category: "عالم الحيوان", q: "كم عدد القلوب التي يمتلكها الأخطبوط؟", a: "3 قلوب", choices: ["قلب واحد", "قلبان", "3 قلوب", "4 قلوب"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/أخطبوط
  { category: "عالم الحيوان", q: "ما هو أكبر حيوان معروف عاش على وجه الأرض حتى الآن؟", a: "الحوت الأزرق", choices: ["الفيل الأفريقي", "الحوت الأزرق", "ديناصور التيريكس", "الزرافة"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/حوت_أزرق
  { category: "عالم الحيوان", q: "أي حيوان يُعرف شعبياً بلقب 'سفينة الصحراء'؟", a: "الجمل", choices: ["الحصان", "الجمل", "اللاما", "المها"], difficulty: "super easy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/جمل
  { category: "عالم الحيوان", q: "ما هي الحشرة المسؤولة عن إنتاج العسل الطبيعي؟", a: "النحل", choices: ["الدبابير", "الفراشات", "النحل", "الخنافس"], difficulty: "super easy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/نحل
  { category: "عالم الحيوان", q: "أي حيوان يُطلق عليه في الثقافة الشعبية لقب 'ملك الغابة'؟", a: "الأسد", choices: ["الأسد", "النمر", "الفهد", "الذئب"], difficulty: "super easy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/أسد
  { category: "عالم الحيوان", q: "ما هو أطول حيوان بري على قيد الحياة بفضل رقبته الطويلة؟", a: "الزرافة", choices: ["الغزال", "الزرافة", "الحمار الوحشي", "اللاما"], difficulty: "super easy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/زرافة
  { category: "عالم الحيوان", q: "أي حيوان أسترالي شهير يملك جيباً يحمل فيه صغيره؟", a: "الكنغر", choices: ["الكوالا", "الكنغر", "القرد", "الباندا"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/كنغريات
  { category: "عالم الحيوان", q: "ما هو الزاحف المعروف بقدرته الفائقة على تغيير لونه للتمويه؟", a: "الحرباء", choices: ["السحلية", "الحرباء", "الأفعى", "الضفدع"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/حرباء
  { category: "جغرافيا وعواصم", q: "ما هي عاصمة جمهورية مصر العربية؟", a: "القاهرة", choices: ["الإسكندرية", "شرم الشيخ", "القاهرة", "الأقصر"], difficulty: "super easy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/القاهرة
  { category: "جغرافيا وعواصم", q: "ما هو النهر الذي يُعتبر الأطول في العالم وفقاً لمعظم المصادر الجغرافية التقليدية؟", a: "نهر النيل", choices: ["نهر الأمازون", "نهر المسيسيبي", "نهر النيل", "نهر الفرات"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/نهر_النيل
  { category: "جغرافيا وعواصم", q: "ما هي أصغر دولة مستقلة في العالم من حيث المساحة؟", a: "الفاتيكان", choices: ["موناكو", "سان مارينو", "جزر المالديف", "الفاتيكان"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/الفاتيكان
  { category: "جغرافيا وعواصم", q: "ما هي عاصمة المملكة العربية السعودية؟", a: "الرياض", choices: ["جدة", "مكة المكرمة", "الرياض", "الدمام"], difficulty: "super easy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/الرياض
  { category: "جغرافيا وعواصم", q: "ما هي عاصمة فرنسا؟", a: "باريس", choices: ["ليون", "باريس", "مرسيليا", "بوردو"], difficulty: "super easy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/باريس
  { category: "جغرافيا وعواصم", q: "ما هو أكبر محيط على كوكب الأرض من حيث المساحة؟", a: "المحيط الهادئ", choices: ["المحيط الأطلسي", "المحيط الهندي", "المحيط الهادئ", "المحيط المتجمد الشمالي"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/المحيط_الهادئ
  { category: "جغرافيا وعواصم", q: "ما هي عاصمة اليابان؟", a: "طوكيو", choices: ["أوساكا", "كيوتو", "طوكيو", "ناغويا"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/طوكيو
  { category: "جغرافيا وعواصم", q: "في أي قارة تقع دولة البرازيل؟", a: "أمريكا الجنوبية", choices: ["أوروبا", "آسيا", "أمريكا الجنوبية", "أفريقيا"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/البرازيل
  { category: "جغرافيا وعواصم", q: "ما هي عاصمة تركيا؟", a: "أنقرة", choices: ["إسطنبول", "أنقرة", "إزمير", "بورصة"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/أنقرة
  { category: "جغرافيا وعواصم", q: "ما هي أكبر قارة في العالم من حيث المساحة وعدد السكان؟", a: "آسيا", choices: ["أوروبا", "آسيا", "أفريقيا", "أمريكا الشمالية"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/آسيا
  { category: "جغرافيا وعواصم", q: "ما هي عاصمة المغرب؟", a: "الرباط", choices: ["مراكش", "الدار البيضاء", "فاس", "الرباط"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/الرباط
  { category: "الفيزياء", q: "ما هي الوحدة الأساسية لقياس القوة في النظام الدولي للوحدات؟", a: "نيوتن", choices: ["جول", "واط", "نيوتن", "أمبير"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/نيوتن_(وحدة)
  { category: "الفيزياء", q: "ما هي سرعة الضوء التقريبية في الفراغ؟", a: "300,000 كم/ث", choices: ["150,000 كم/ث", "300,000 كم/ث", "30,000 كم/ث", "3,000 كم/ث"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/سرعة_الضوء
  { category: "الكيمياء", q: "ما هو الرمز الكيميائي لعنصر الأكسجين؟", a: "O", choices: ["Ox", "O", "Og", "Om"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/أكسجين
  { category: "الأحياء", q: "ما هي الوحدة الأساسية لبناء جميع الكائنات الحية؟", a: "الخلية", choices: ["النسيج", "الخلية", "العضو", "الجهاز"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/خلية
  { category: "الأحياء", q: "أي عضو رئيسي في جسم الإنسان مسؤول عن ضخ الدم إلى باقي الأعضاء؟", a: "القلب", choices: ["الرئتان", "الكبد", "القلب", "الكلى"], difficulty: "super easy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/قلب
  { category: "الكيمياء", q: "ما هي الحالة الفيزيائية للماء النقي عند درجة حرارة الغرفة؟", a: "سائل", choices: ["صلب", "غاز", "سائل", "بلازما"], difficulty: "super easy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/ماء
  { category: "الفيزياء", q: "ما هو الجهاز المستخدم لقياس درجة الحرارة؟", a: "الترمومتر", choices: ["البارومتر", "الترمومتر", "الأميتر", "الفولتميتر"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/مقياس_حرارة
  { category: "الأحياء", q: "أي جزء من النبات يقوم بعملية البناء الضوئي بشكل رئيسي؟", a: "الورقة", choices: ["الجذر", "الساق", "الورقة", "الزهرة"], difficulty: "easy", points: 100, power: false }, // Source: https://ar.wikipedia.org/wiki/تمثيل_ضوئي
  { category: "الكيمياء", q: "ما هو الغاز الحيوي الذي يحتاجه الإنسان للتنفس بشكل أساسي؟", a: "الأكسجين", choices: ["الهيدروجين", "الأكسجين", "النيتروجين", "ثاني أكسيد الكربون"], difficulty: "super easy", points: 50, power: false }, // Source: https://ar.wikipedia.org/wiki/تنفس
  { category: "الفيزياء", q: "ما هي وحدة قياس الطاقة في النظام الدولي للوحدات؟", a: "جول", choices: ["نيوتن", "جول", "واط", "فولت"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/جول
  { category: "الكيمياء", q: "ما هو الغاز الرئيسي المرتبط بظاهرة الاحتباس الحراري الناتجة عن النشاط البشري؟", a: "ثاني أكسيد الكربون", choices: ["الأكسجين", "النيتروجين", "ثاني أكسيد الكربون", "الهيدروجين"], difficulty: "medium", points: 150, power: false }, // Source: https://ar.wikipedia.org/wiki/غاز_دفيئة
  { category: "الأحياء", q: "ما هو العضو الرئيسي المسؤول عن تنقية الدم من الفضلات السائلة في جسم الإنسان؟", a: "الكلى", choices: ["القلب", "الكبد", "الكلى", "الرئة"], difficulty: "medium", points: 150, power: false } // Source: https://ar.wikipedia.org/wiki/كلية
];